#!/bin/bash -e
if [[ -z $HAM_PROJECT_DIR ]]; then
  echo "E/HAM_PROJECT_DIR not set !"
  return 1
fi

export PM2_ENV_NAME=niLang

# Base toolsets
TOOLSET_LIST=(repos)

# Platform specific toolsets
case $HAM_OS in
  NT*)
    TOOLSET_LIST+=(dx9sdk2004)
    # The shader compiler is enabled by default on Windows
    if [ -z "$SHADER_COMPILE" ]; then
      SHADER_COMPILE=1
    fi
    ;;
  LINUX*)
    TOOLSET_LIST+=(syslib_libdw syslib_alsa)
    # TOOLSET_LIST+=(syslib_bfd)
    ;;
  OSX*)
    TOOLSET_LIST+=(vulkan_sdk)
    ;;
  *) ;;
esac

# Shader compiler
if [ "$SHADER_COMPILE" = "1" ]; then
  TOOLSET_LIST+=(nicgc)
  export SHADER_COMPILE=1
else
  unset SHADER_COMPILE
  log_info "No shader compilation."
fi

# C++ toolsets
TOOLSET_LIST+=(cppm)

# Done, import our toolsets...
toolset_import_list "${TOOLSET_LIST[@]}" || return 1
