#!/bin/bash -e
if [[ -z $HAM_PROJECT_DIR ]]; then
    echo "E/HAM_PROJECT_DIR not set !"
    return 1
fi

export PM2_ENV_NAME=niLang

BUILD_TARGET=${BUILD_TARGET:-default}
CPP_TOOLSET=$(ham-cppm-get-toolset "${BUILD_TARGET}")
retcheck $? "Can't get C++ toolset for BUILD_TARGET '$BUILD_TARGET'." || return 1

case $HAM_OS in
    NT*)
        toolset_import_list "repos" "dx9sdk2004" "$CPP_TOOLSET" boost_cppm thrift_cppm || return 1
        ;;
    *)
        toolset_import_list "repos" "$CPP_TOOLSET" boost_cppm thrift_cppm || return 1
        ;;
esac
