#pragma once
#ifndef __SQ_HSTRING_H_A4DC9B91_9066_EF11_8442_711111AD5543__
#define __SQ_HSTRING_H_A4DC9B91_9066_EF11_8442_711111AD5543__

_HDecl(_all);
_HDecl(_pedantic);
_HDecl(_experimental);
_HDecl(_explicit);
_HDecl(__debug_name);
_HDecl(__lint);
_HDecl(no_debug_name);
_HDecl(IDENTIFIER);
_HDecl(STRING_LITERAL);
_HDecl(INTEGER);
_HDecl(FLOAT);
_HDecl(NEWSLOT);
_HDecl(this);
_HDecl(__this__);
_HDecl(__this_module__);
_HDecl(__root_table__);
_HDecl(compilecontext);
_HDecl_(AT_ITERATOR_AT,"@ITERATOR@");
_HDecl_(AT_INDEX_AT,"@INDEX@");
_HDecl(func);
_HDecl(src);
_HDecl(line);
_HDecl(col);
_HDecl(locals);
_HDecl(Import);
_HDecl(NewImport);
_HDecl(method);
_HDecl(interface);
_HDecl(Vec2);
_HDecl(Vec3);
_HDecl(Vec4);
_HDecl(Matrix);
_HDecl(UUID);
_HDecl_(NOT_ITOSTRING,"[not iToString]");
_HDecl(e);
_HDecl(error_code);
_HDecl(error_code_unknown_typedef);
_HDecl(error_code_cant_load_module_def);
_HDecl(error_code_cant_find_interface_def);
_HDecl(error_code_cant_find_method_def);
_HDecl(error_code_method_def_invalid_ret_type);
_HDecl(error_code_cant_find_type_uuid);
_HDecl(error_code_lint_call_error);
_HDecl(error_code_dangling_type);
_HDecl(error_code_cant_resolve_table_type_path);
_HDecl(error_code_out_of_range);
_HDecl(error_code_cant_find_registered_type);
_HDecl(error_code_import_native);
_HDecl(resolved_type);
_HDecl(QueryInterface);
_HDecl_(typestr_null, "null");
_HDecl_(typestr_int, "int");
_HDecl_(typestr_float, "float");
_HDecl_(typestr_string, "string");
_HDecl_(typestr_table, "table");
_HDecl_(typestr_array, "array");
_HDecl_(typestr_function, "function");
_HDecl_(typestr_userdata, "userdata");
_HDecl_(typestr_iunknown, "iunknown");
_HDecl_(typestr_closure, "closure");
_HDecl_(typestr_nativeclosure, "nativeclosure");
_HDecl_(typestr_functionproto, "functionproto");
_HDecl_(typestr_indexed_property, "indexed_property");
_HDecl_(typestr_iterator, "iterator");
_HDecl_(typestr_enum, "enum");
_HDecl_(typestr_property, "property");
_HDecl_(typestr_invalid, "invalid");
_HDecl_(typestr_void, "void");
_HDecl_(typestr_bool, "bool");
_HDecl_(typestr_iHStringCharIt, "iHStringCharIt");
_HDecl_(typestr_iMutableCollection, "iMutableCollection");
_HDecl_(typestr_iCollection, "iCollection");
_HDecl_(typestr_iScriptObject, "iScriptObject");
_HDecl_(typestr_iScriptVM, "iScriptVM");
_HDecl(_args_);

#endif // __SQ_HSTRING_H_A4DC9B91_9066_EF11_8442_711111AD5543__
