// clang-format off
#ifndef __MODULEDEF_Test_niScriptCpp_Module_H__
#define __MODULEDEF_Test_niScriptCpp_Module_H__
/*
 * Autogenerated module definition for ::Test_niScriptCpp_Module.
 */

#include <niLang/ObjModel.h>

namespace  {
/** \addtogroup niLang
 * @{
 */

static const char *const kVersion_Test_niScriptCpp_Module = "1,0,0";
niExportFunc(const ni::iModuleDef*) GetModuleDef_Test_niScriptCpp_Module();


/**@}*/
} // end of namespace 

/// EOF //////////////////////////////////////////////////////////////////////////////////////
#endif /// __MODULEDEF_Test_niScriptCpp_Module_H__
