// clang-format off
//
// Autogenerated IDL definition for 'API/niScriptCpp/ScriptCpp.h'.
//
#include "../API/niScriptCpp/ScriptCpp.h"

#ifndef IDLC_BEGIN_NAMESPACE
#error "IDLC_BEGIN_NAMESPACE not defined !"
#endif
#ifndef IDLC_END_NAMESPACE
#error "IDLC_END_NAMESPACE not defined !"
#endif

IDLC_BEGIN_NAMESPACE()

/** NAMESPACE : ni **/
/** struct : sScriptCppModuleCache **/
/** sScriptCppModuleCache -> NO AUTOMATION **/

/** struct : sScriptCppStats **/
/** sScriptCppStats -> NO AUTOMATION **/

IDLC_END_NAMESPACE()
// EOF //
