TSGL_CORE_PROC(void        ,glActiveTexture, (GLenum texture));
TSGL_CORE_PROC(void        ,glAttachShader, (GLuint program, GLuint shader));
TSGL_CORE_PROC(void        ,glBindAttribLocation, (GLuint program, GLuint index, const char* name));
TSGL_CORE_PROC(void        ,glBindBuffer, (GLenum target, GLuint buffer));
TSGL_CORE_PROC(void        ,glBindFramebuffer, (GLenum target, GLuint framebuffer));
TSGL_CORE_PROC(void        ,glBindRenderbuffer, (GLenum target, GLuint renderbuffer));
TSGL_CORE_PROC(void        ,glBindTexture, (GLenum target, GLuint texture));
TSGL_CORE_PROC(void        ,glBlendColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TSGL_CORE_PROC(void        ,glBlendEquation, ( GLenum mode ));
TSGL_CORE_PROC(void        ,glBlendEquationSeparate, (GLenum modeRGB, GLenum modeAlpha));
TSGL_CORE_PROC(void        ,glBlendFunc, (GLenum sfactor, GLenum dfactor));
TSGL_CORE_PROC(void        ,glBlendFuncSeparate, (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha));
TSGL_CORE_PROC(void        ,glBufferData, (GLenum target, GLsizeiptr size, const void* data, GLenum usage));
TSGL_CORE_PROC(void        ,glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const void* data));
TSGL_CORE_PROC(GLenum      ,glCheckFramebufferStatus, (GLenum target));
TSGL_CORE_PROC(void        ,glClear, (GLbitfield mask));
TSGL_CORE_PROC(void        ,glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TSGL_CORE_PROC(void        ,glClearDepthf, (GLclampf depth));
TSGL_CORE_PROC(void        ,glClearStencil, (GLint s));
TSGL_CORE_PROC(void        ,glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
TSGL_CORE_PROC(void        ,glCompileShader, (GLuint shader));
TSGL_CORE_PROC(void        ,glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data));
TSGL_CORE_PROC(void        ,glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data));
TSGL_CORE_PROC(void        ,glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
TSGL_CORE_PROC(void        ,glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(GLuint      ,glCreateProgram, (void));
TSGL_CORE_PROC(GLuint      ,glCreateShader, (GLenum type));
TSGL_CORE_PROC(void        ,glCullFace, (GLenum mode));
TSGL_CORE_PROC(void        ,glDeleteBuffers, (GLsizei n, const GLuint* buffers));
TSGL_CORE_PROC(void        ,glDeleteFramebuffers, (GLsizei n, const GLuint* framebuffers));
TSGL_CORE_PROC(void        ,glDeleteProgram, (GLuint program));
TSGL_CORE_PROC(void        ,glDeleteRenderbuffers, (GLsizei n, const GLuint* renderbuffers));
TSGL_CORE_PROC(void        ,glDeleteShader, (GLuint shader));
TSGL_CORE_PROC(void        ,glDeleteTextures, (GLsizei n, const GLuint* textures));
TSGL_CORE_PROC(void        ,glDepthFunc, (GLenum func));
TSGL_CORE_PROC(void        ,glDepthMask, (GLboolean flag));
TSGL_CORE_PROC(void        ,glDepthRangef, (GLclampf zNear, GLclampf zFar));
TSGL_CORE_PROC(void        ,glDetachShader, (GLuint program, GLuint shader));
TSGL_CORE_PROC(void        ,glDisable, (GLenum cap));
TSGL_CORE_PROC(void        ,glDisableVertexAttribArray, (GLuint index));
TSGL_CORE_PROC(void        ,glDrawArrays, (GLenum mode, GLint first, GLsizei count));
TSGL_CORE_PROC(void        ,glDrawElements, (GLenum mode, GLsizei count, GLenum type, const void* indices));
TSGL_CORE_PROC(void        ,glEnable, (GLenum cap));
TSGL_CORE_PROC(void        ,glEnableVertexAttribArray, (GLuint index));
TSGL_CORE_PROC(void        ,glFinish, (void));
TSGL_CORE_PROC(void        ,glFlush, (void));
TSGL_CORE_PROC(void        ,glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer));
TSGL_CORE_PROC(void        ,glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level));
TSGL_CORE_PROC(void        ,glFrontFace, (GLenum mode));
TSGL_CORE_PROC(void        ,glGenBuffers, (GLsizei n, GLuint* buffers));
TSGL_CORE_PROC(void        ,glGenerateMipmap, (GLenum target));
TSGL_CORE_PROC(void        ,glGenFramebuffers, (GLsizei n, GLuint* framebuffers));
TSGL_CORE_PROC(void        ,glGenRenderbuffers, (GLsizei n, GLuint* renderbuffers));
TSGL_CORE_PROC(void        ,glGenTextures, (GLsizei n, GLuint* textures));
TSGL_CORE_PROC(void        ,glGetActiveAttrib, (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name));
TSGL_CORE_PROC(void        ,glGetActiveUniform, (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name));
TSGL_CORE_PROC(void        ,glGetAttachedShaders, (GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders));
TSGL_CORE_PROC(int         ,glGetAttribLocation, (GLuint program, const char* name));
TSGL_CORE_PROC(void        ,glGetBooleanv, (GLenum pname, GLboolean* params));
TSGL_CORE_PROC(void        ,glGetBufferParameteriv, (GLenum target, GLenum pname, GLint* params));
TSGL_CORE_PROC(GLenum      ,glGetError, (void));
TSGL_CORE_PROC(void        ,glGetFloatv, (GLenum pname, GLfloat* params));
TSGL_CORE_PROC(void        ,glGetFramebufferAttachmentParameteriv, (GLenum target, GLenum attachment, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetIntegerv, (GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetProgramiv, (GLuint program, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetProgramInfoLog, (GLuint program, GLsizei bufsize, GLsizei* length, char* infolog));
TSGL_CORE_PROC(void        ,glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetShaderiv, (GLuint shader, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetShaderInfoLog, (GLuint shader, GLsizei bufsize, GLsizei* length, char* infolog));
TSGL_CORE_PROC(void        ,glGetShaderPrecisionFormat, (GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision));
TSGL_CORE_PROC(void        ,glGetShaderSource, (GLuint shader, GLsizei bufsize, GLsizei* length, char* source));
TSGL_CORE_PROC(const GLubyte*,glGetString, (GLenum name));
TSGL_CORE_PROC(void        ,glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat* params));
TSGL_CORE_PROC(void        ,glGetTexParameteriv, (GLenum target, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetUniformfv, (GLuint program, GLint location, GLfloat* params));
TSGL_CORE_PROC(void        ,glGetUniformiv, (GLuint program, GLint location, GLint* params));
TSGL_CORE_PROC(int         ,glGetUniformLocation, (GLuint program, const char* name));
TSGL_CORE_PROC(void        ,glGetVertexAttribfv, (GLuint index, GLenum pname, GLfloat* params));
TSGL_CORE_PROC(void        ,glGetVertexAttribiv, (GLuint index, GLenum pname, GLint* params));
TSGL_CORE_PROC(void        ,glGetVertexAttribPointerv, (GLuint index, GLenum pname, void** pointer));
TSGL_CORE_PROC(void        ,glHint, (GLenum target, GLenum mode));
TSGL_CORE_PROC(GLboolean   ,glIsBuffer, (GLuint buffer));
TSGL_CORE_PROC(GLboolean   ,glIsEnabled, (GLenum cap));
TSGL_CORE_PROC(GLboolean   ,glIsFramebuffer, (GLuint framebuffer));
TSGL_CORE_PROC(GLboolean   ,glIsProgram, (GLuint program));
TSGL_CORE_PROC(GLboolean   ,glIsRenderbuffer, (GLuint renderbuffer));
TSGL_CORE_PROC(GLboolean   ,glIsShader, (GLuint shader));
TSGL_CORE_PROC(GLboolean   ,glIsTexture, (GLuint texture));
TSGL_CORE_PROC(void        ,glLineWidth, (GLfloat width));
TSGL_CORE_PROC(void        ,glLinkProgram, (GLuint program));
TSGL_CORE_PROC(void        ,glPixelStorei, (GLenum pname, GLint param));
TSGL_CORE_PROC(void        ,glPolygonOffset, (GLfloat factor, GLfloat units));
TSGL_CORE_PROC(void        ,glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels));
TSGL_CORE_PROC(void        ,glReleaseShaderCompiler, (void));
TSGL_CORE_PROC(void        ,glRenderbufferStorage, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void        ,glSampleCoverage, (GLclampf value, GLboolean invert));
TSGL_CORE_PROC(void        ,glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void        ,glShaderBinary, (GLsizei n, const GLuint* shaders, GLenum binaryformat, const void* binary, GLsizei length));
TSGL_CORE_PROC(void        ,glShaderSource, (GLuint shader, GLsizei count, const char** string, const GLint* length));
TSGL_CORE_PROC(void        ,glStencilFunc, (GLenum func, GLint ref, GLuint mask));
TSGL_CORE_PROC(void        ,glStencilFuncSeparate, (GLenum face, GLenum func, GLint ref, GLuint mask));
TSGL_CORE_PROC(void        ,glStencilMask, (GLuint mask));
TSGL_CORE_PROC(void        ,glStencilMaskSeparate, (GLenum face, GLuint mask));
TSGL_CORE_PROC(void        ,glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
TSGL_CORE_PROC(void        ,glStencilOpSeparate, (GLenum face, GLenum fail, GLenum zfail, GLenum zpass));
TSGL_CORE_PROC(void        ,glTexImage2D, (GLenum target, GLint level, GLint internalformat,  GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels));
TSGL_CORE_PROC(void        ,glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void        ,glTexParameterfv, (GLenum target, GLenum pname, const GLfloat* params));
TSGL_CORE_PROC(void        ,glTexParameteri, (GLenum target, GLenum pname, GLint param));
TSGL_CORE_PROC(void        ,glTexParameteriv, (GLenum target, GLenum pname, const GLint* params));
TSGL_CORE_PROC(void        ,glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels));
TSGL_CORE_PROC(void        ,glUniform1f, (GLint location, GLfloat x));
TSGL_CORE_PROC(void        ,glUniform1fv, (GLint location, GLsizei count, const GLfloat* v));
TSGL_CORE_PROC(void        ,glUniform1i, (GLint location, GLint x));
TSGL_CORE_PROC(void        ,glUniform1iv, (GLint location, GLsizei count, const GLint* v));
TSGL_CORE_PROC(void        ,glUniform2f, (GLint location, GLfloat x, GLfloat y));
TSGL_CORE_PROC(void        ,glUniform2fv, (GLint location, GLsizei count, const GLfloat* v));
TSGL_CORE_PROC(void        ,glUniform2i, (GLint location, GLint x, GLint y));
TSGL_CORE_PROC(void        ,glUniform2iv, (GLint location, GLsizei count, const GLint* v));
TSGL_CORE_PROC(void        ,glUniform3f, (GLint location, GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void        ,glUniform3fv, (GLint location, GLsizei count, const GLfloat* v));
TSGL_CORE_PROC(void        ,glUniform3i, (GLint location, GLint x, GLint y, GLint z));
TSGL_CORE_PROC(void        ,glUniform3iv, (GLint location, GLsizei count, const GLint* v));
TSGL_CORE_PROC(void        ,glUniform4f, (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TSGL_CORE_PROC(void        ,glUniform4fv, (GLint location, GLsizei count, const GLfloat* v));
TSGL_CORE_PROC(void        ,glUniform4i, (GLint location, GLint x, GLint y, GLint z, GLint w));
TSGL_CORE_PROC(void        ,glUniform4iv, (GLint location, GLsizei count, const GLint* v));
TSGL_CORE_PROC(void        ,glUniformMatrix2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
TSGL_CORE_PROC(void        ,glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
TSGL_CORE_PROC(void        ,glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
TSGL_CORE_PROC(void        ,glUseProgram, (GLuint program));
TSGL_CORE_PROC(void        ,glValidateProgram, (GLuint program));
TSGL_CORE_PROC(void        ,glVertexAttrib1f, (GLuint indx, GLfloat x));
TSGL_CORE_PROC(void        ,glVertexAttrib1fv, (GLuint indx, const GLfloat* values));
TSGL_CORE_PROC(void        ,glVertexAttrib2f, (GLuint indx, GLfloat x, GLfloat y));
TSGL_CORE_PROC(void        ,glVertexAttrib2fv, (GLuint indx, const GLfloat* values));
TSGL_CORE_PROC(void        ,glVertexAttrib3f, (GLuint indx, GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void        ,glVertexAttrib3fv, (GLuint indx, const GLfloat* values));
TSGL_CORE_PROC(void        ,glVertexAttrib4f, (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TSGL_CORE_PROC(void        ,glVertexAttrib4fv, (GLuint indx, const GLfloat* values));
TSGL_CORE_PROC(void        ,glVertexAttribPointer, (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* ptr));
TSGL_CORE_PROC(void        ,glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));
