TSGL_CORE_PROC(void, glAccum, (GLenum op, GLfloat value));
TSGL_CORE_PROC(void, glAlphaFunc, (GLenum func, GLclampf ref));
TSGL_CORE_PROC(GLboolean, glAreTexturesResident, (GLsizei n, const GLuint *textures, GLboolean *residences));
TSGL_CORE_PROC(void, glArrayElement, (GLint i));
TSGL_CORE_PROC(void, glBegin, (GLenum mode));
TSGL_CORE_PROC(void, glBindTexture, (GLenum target, GLuint texture));
TSGL_CORE_PROC(void, glBitmap, (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap));
TSGL_CORE_PROC(void, glBlendFunc, (GLenum sfactor, GLenum dfactor));
TSGL_CORE_PROC(void, glCallList, (GLuint list));
TSGL_CORE_PROC(void, glCallLists, (GLsizei n, GLenum type, const GLvoid *lists));
TSGL_CORE_PROC(void, glClear, (GLbitfield mask));
TSGL_CORE_PROC(void, glClearAccum, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TSGL_CORE_PROC(void, glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TSGL_CORE_PROC(void, glClearDepth, (GLclampd depth));
TSGL_CORE_PROC(void, glClearIndex, (GLfloat c));
TSGL_CORE_PROC(void, glClearStencil, (GLint s));
TSGL_CORE_PROC(void, glClipPlane, (GLenum plane, const GLdouble *equation));
TSGL_CORE_PROC(void, glColor3b, (GLbyte red, GLbyte green, GLbyte blue));
TSGL_CORE_PROC(void, glColor3bv, (const GLbyte *v));
TSGL_CORE_PROC(void, glColor3d, (GLdouble red, GLdouble green, GLdouble blue));
TSGL_CORE_PROC(void, glColor3dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glColor3f, (GLfloat red, GLfloat green, GLfloat blue));
TSGL_CORE_PROC(void, glColor3fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glColor3i, (GLint red, GLint green, GLint blue));
TSGL_CORE_PROC(void, glColor3iv, (const GLint *v));
TSGL_CORE_PROC(void, glColor3s, (GLshort red, GLshort green, GLshort blue));
TSGL_CORE_PROC(void, glColor3sv, (const GLshort *v));
TSGL_CORE_PROC(void, glColor3ub, (GLubyte red, GLubyte green, GLubyte blue));
TSGL_CORE_PROC(void, glColor3ubv, (const GLubyte *v));
TSGL_CORE_PROC(void, glColor3ui, (GLuint red, GLuint green, GLuint blue));
TSGL_CORE_PROC(void, glColor3uiv, (const GLuint *v));
TSGL_CORE_PROC(void, glColor3us, (GLushort red, GLushort green, GLushort blue));
TSGL_CORE_PROC(void, glColor3usv, (const GLushort *v));
TSGL_CORE_PROC(void, glColor4b, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha));
TSGL_CORE_PROC(void, glColor4bv, (const GLbyte *v));
TSGL_CORE_PROC(void, glColor4d, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha));
TSGL_CORE_PROC(void, glColor4dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TSGL_CORE_PROC(void, glColor4fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glColor4i, (GLint red, GLint green, GLint blue, GLint alpha));
TSGL_CORE_PROC(void, glColor4iv, (const GLint *v));
TSGL_CORE_PROC(void, glColor4s, (GLshort red, GLshort green, GLshort blue, GLshort alpha));
TSGL_CORE_PROC(void, glColor4sv, (const GLshort *v));
TSGL_CORE_PROC(void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
TSGL_CORE_PROC(void, glColor4ubv, (const GLubyte *v));
TSGL_CORE_PROC(void, glColor4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha));
TSGL_CORE_PROC(void, glColor4uiv, (const GLuint *v));
TSGL_CORE_PROC(void, glColor4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha));
TSGL_CORE_PROC(void, glColor4usv, (const GLushort *v));
TSGL_CORE_PROC(void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
TSGL_CORE_PROC(void, glColorMaterial, (GLenum face, GLenum mode));
TSGL_CORE_PROC(void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glCopyPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type));
TSGL_CORE_PROC(void, glCopyTexImage1D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border));
TSGL_CORE_PROC(void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
TSGL_CORE_PROC(void, glCopyTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width));
TSGL_CORE_PROC(void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void, glCullFace, (GLenum mode));
TSGL_CORE_PROC(void, glDeleteLists, (GLuint list, GLsizei range));
TSGL_CORE_PROC(void, glDeleteTextures, (GLsizei n, const GLuint *textures));
TSGL_CORE_PROC(void, glDepthFunc, (GLenum func));
TSGL_CORE_PROC(void, glDepthMask, (GLboolean flag));
TSGL_CORE_PROC(void, glDepthRange, (GLclampd zNear, GLclampd zFar));
TSGL_CORE_PROC(void, glDisable, (GLenum cap));
TSGL_CORE_PROC(void, glDisableClientState, (GLenum array));
TSGL_CORE_PROC(void, glDrawArrays, (GLenum mode, GLint first, GLsizei count));
TSGL_CORE_PROC(void, glDrawBuffer, (GLenum mode));
TSGL_CORE_PROC(void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices));
TSGL_CORE_PROC(void, glDrawPixels, (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void, glEdgeFlag, (GLboolean flag));
TSGL_CORE_PROC(void, glEdgeFlagPointer, (GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glEdgeFlagv, (const GLboolean *flag));
TSGL_CORE_PROC(void, glEnable, (GLenum cap));
TSGL_CORE_PROC(void, glEnableClientState, (GLenum array));
TSGL_CORE_PROC(void, glEnd, (void));
TSGL_CORE_PROC(void, glEndList, (void));
TSGL_CORE_PROC(void, glEvalCoord1d, (GLdouble u));
TSGL_CORE_PROC(void, glEvalCoord1dv, (const GLdouble *u));
TSGL_CORE_PROC(void, glEvalCoord1f, (GLfloat u));
TSGL_CORE_PROC(void, glEvalCoord1fv, (const GLfloat *u));
TSGL_CORE_PROC(void, glEvalCoord2d, (GLdouble u, GLdouble v));
TSGL_CORE_PROC(void, glEvalCoord2dv, (const GLdouble *u));
TSGL_CORE_PROC(void, glEvalCoord2f, (GLfloat u, GLfloat v));
TSGL_CORE_PROC(void, glEvalCoord2fv, (const GLfloat *u));
TSGL_CORE_PROC(void, glEvalMesh1, (GLenum mode, GLint i1, GLint i2));
TSGL_CORE_PROC(void, glEvalMesh2, (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2));
TSGL_CORE_PROC(void, glEvalPoint1, (GLint i));
TSGL_CORE_PROC(void, glEvalPoint2, (GLint i, GLint j));
TSGL_CORE_PROC(void, glFeedbackBuffer, (GLsizei size, GLenum type, GLfloat *buffer));
TSGL_CORE_PROC(void, glFinish, (void));
TSGL_CORE_PROC(void, glFlush, (void));
TSGL_CORE_PROC(void, glFogf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glFogfv, (GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glFogi, (GLenum pname, GLint param));
TSGL_CORE_PROC(void, glFogiv, (GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glFrontFace, (GLenum mode));
TSGL_CORE_PROC(void, glFrustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar));
TSGL_CORE_PROC(GLuint, glGenLists, (GLsizei range));
TSGL_CORE_PROC(void, glGenTextures, (GLsizei n, GLuint *textures));
TSGL_CORE_PROC(void, glGetBooleanv, (GLenum pname, GLboolean *params));
TSGL_CORE_PROC(void, glGetClipPlane, (GLenum plane, GLdouble *equation));
TSGL_CORE_PROC(void, glGetDoublev, (GLenum pname, GLdouble *params));
TSGL_CORE_PROC(GLenum, glGetError, (void));
TSGL_CORE_PROC(void, glGetFloatv, (GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetIntegerv, (GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetLightfv, (GLenum light, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetLightiv, (GLenum light, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetMapdv, (GLenum target, GLenum query, GLdouble *v));
TSGL_CORE_PROC(void, glGetMapfv, (GLenum target, GLenum query, GLfloat *v));
TSGL_CORE_PROC(void, glGetMapiv, (GLenum target, GLenum query, GLint *v));
TSGL_CORE_PROC(void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetMaterialiv, (GLenum face, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetPixelMapfv, (GLenum map, GLfloat *values));
TSGL_CORE_PROC(void, glGetPixelMapuiv, (GLenum map, GLuint *values));
TSGL_CORE_PROC(void, glGetPixelMapusv, (GLenum map, GLushort *values));
TSGL_CORE_PROC(void, glGetPointerv, (GLenum pname, GLvoid* *params));
TSGL_CORE_PROC(void, glGetPolygonStipple, (GLubyte *mask));
TSGL_CORE_PROC(const GLubyte*, glGetString, (GLenum name));
TSGL_CORE_PROC(void, glGetTexEnvfv, (GLenum target, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetTexEnviv, (GLenum target, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetTexGendv, (GLenum coord, GLenum pname, GLdouble *params));
TSGL_CORE_PROC(void, glGetTexGenfv, (GLenum coord, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetTexGeniv, (GLenum coord, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels));
TSGL_CORE_PROC(void, glGetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint *params));
TSGL_CORE_PROC(void, glHint, (GLenum target, GLenum mode));
TSGL_CORE_PROC(void, glIndexMask, (GLuint mask));
TSGL_CORE_PROC(void, glIndexPointer, (GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glIndexd, (GLdouble c));
TSGL_CORE_PROC(void, glIndexdv, (const GLdouble *c));
TSGL_CORE_PROC(void, glIndexf, (GLfloat c));
TSGL_CORE_PROC(void, glIndexfv, (const GLfloat *c));
TSGL_CORE_PROC(void, glIndexi, (GLint c));
TSGL_CORE_PROC(void, glIndexiv, (const GLint *c));
TSGL_CORE_PROC(void, glIndexs, (GLshort c));
TSGL_CORE_PROC(void, glIndexsv, (const GLshort *c));
TSGL_CORE_PROC(void, glIndexub, (GLubyte c));
TSGL_CORE_PROC(void, glIndexubv, (const GLubyte *c));
TSGL_CORE_PROC(void, glInitNames, (void));
TSGL_CORE_PROC(void, glInterleavedArrays, (GLenum format, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(GLboolean, glIsEnabled, (GLenum cap));
TSGL_CORE_PROC(GLboolean, glIsList, (GLuint list));
TSGL_CORE_PROC(GLboolean, glIsTexture, (GLuint texture));
TSGL_CORE_PROC(void, glLightModelf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glLightModelfv, (GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glLightModeli, (GLenum pname, GLint param));
TSGL_CORE_PROC(void, glLightModeliv, (GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glLightf, (GLenum light, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glLightfv, (GLenum light, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glLighti, (GLenum light, GLenum pname, GLint param));
TSGL_CORE_PROC(void, glLightiv, (GLenum light, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glLineStipple, (GLint factor, GLushort pattern));
TSGL_CORE_PROC(void, glLineWidth, (GLfloat width));
TSGL_CORE_PROC(void, glListBase, (GLuint base));
TSGL_CORE_PROC(void, glLoadIdentity, (void));
TSGL_CORE_PROC(void, glLoadMatrixd, (const GLdouble *m));
TSGL_CORE_PROC(void, glLoadMatrixf, (const GLfloat *m));
TSGL_CORE_PROC(void, glLoadName, (GLuint name));
TSGL_CORE_PROC(void, glLogicOp, (GLenum opcode));
TSGL_CORE_PROC(void, glMap1d, (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points));
TSGL_CORE_PROC(void, glMap1f, (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points));
TSGL_CORE_PROC(void, glMap2d, (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points));
TSGL_CORE_PROC(void, glMap2f, (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points));
TSGL_CORE_PROC(void, glMapGrid1d, (GLint un, GLdouble u1, GLdouble u2));
TSGL_CORE_PROC(void, glMapGrid1f, (GLint un, GLfloat u1, GLfloat u2));
TSGL_CORE_PROC(void, glMapGrid2d, (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2));
TSGL_CORE_PROC(void, glMapGrid2f, (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2));
TSGL_CORE_PROC(void, glMaterialf, (GLenum face, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glMateriali, (GLenum face, GLenum pname, GLint param));
TSGL_CORE_PROC(void, glMaterialiv, (GLenum face, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glMatrixMode, (GLenum mode));
TSGL_CORE_PROC(void, glMultMatrixd, (const GLdouble *m));
TSGL_CORE_PROC(void, glMultMatrixf, (const GLfloat *m));
TSGL_CORE_PROC(void, glNewList, (GLuint list, GLenum mode));
TSGL_CORE_PROC(void, glNormal3b, (GLbyte nx, GLbyte ny, GLbyte nz));
TSGL_CORE_PROC(void, glNormal3bv, (const GLbyte *v));
TSGL_CORE_PROC(void, glNormal3d, (GLdouble nx, GLdouble ny, GLdouble nz));
TSGL_CORE_PROC(void, glNormal3dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz));
TSGL_CORE_PROC(void, glNormal3fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glNormal3i, (GLint nx, GLint ny, GLint nz));
TSGL_CORE_PROC(void, glNormal3iv, (const GLint *v));
TSGL_CORE_PROC(void, glNormal3s, (GLshort nx, GLshort ny, GLshort nz));
TSGL_CORE_PROC(void, glNormal3sv, (const GLshort *v));
TSGL_CORE_PROC(void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glOrtho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar));
TSGL_CORE_PROC(void, glPassThrough, (GLfloat token));
TSGL_CORE_PROC(void, glPixelMapfv, (GLenum map, GLsizei mapsize, const GLfloat *values));
TSGL_CORE_PROC(void, glPixelMapuiv, (GLenum map, GLsizei mapsize, const GLuint *values));
TSGL_CORE_PROC(void, glPixelMapusv, (GLenum map, GLsizei mapsize, const GLushort *values));
TSGL_CORE_PROC(void, glPixelStoref, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glPixelStorei, (GLenum pname, GLint param));
TSGL_CORE_PROC(void, glPixelTransferf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glPixelTransferi, (GLenum pname, GLint param));
TSGL_CORE_PROC(void, glPixelZoom, (GLfloat xfactor, GLfloat yfactor));
TSGL_CORE_PROC(void, glPointSize, (GLfloat size));
TSGL_CORE_PROC(void, glPolygonMode, (GLenum face, GLenum mode));
TSGL_CORE_PROC(void, glPolygonOffset, (GLfloat factor, GLfloat units));
TSGL_CORE_PROC(void, glPolygonStipple, (const GLubyte *mask));
TSGL_CORE_PROC(void, glPopAttrib, (void));
TSGL_CORE_PROC(void, glPopClientAttrib, (void));
TSGL_CORE_PROC(void, glPopMatrix, (void));
TSGL_CORE_PROC(void, glPopName, (void));
TSGL_CORE_PROC(void, glPrioritizeTextures, (GLsizei n, const GLuint *textures, const GLclampf *priorities));
TSGL_CORE_PROC(void, glPushAttrib, (GLbitfield mask));
TSGL_CORE_PROC(void, glPushClientAttrib, (GLbitfield mask));
TSGL_CORE_PROC(void, glPushMatrix, (void));
TSGL_CORE_PROC(void, glPushName, (GLuint name));
TSGL_CORE_PROC(void, glRasterPos2d, (GLdouble x, GLdouble y));
TSGL_CORE_PROC(void, glRasterPos2dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glRasterPos2f, (GLfloat x, GLfloat y));
TSGL_CORE_PROC(void, glRasterPos2fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glRasterPos2i, (GLint x, GLint y));
TSGL_CORE_PROC(void, glRasterPos2iv, (const GLint *v));
TSGL_CORE_PROC(void, glRasterPos2s, (GLshort x, GLshort y));
TSGL_CORE_PROC(void, glRasterPos2sv, (const GLshort *v));
TSGL_CORE_PROC(void, glRasterPos3d, (GLdouble x, GLdouble y, GLdouble z));
TSGL_CORE_PROC(void, glRasterPos3dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glRasterPos3f, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void, glRasterPos3fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glRasterPos3i, (GLint x, GLint y, GLint z));
TSGL_CORE_PROC(void, glRasterPos3iv, (const GLint *v));
TSGL_CORE_PROC(void, glRasterPos3s, (GLshort x, GLshort y, GLshort z));
TSGL_CORE_PROC(void, glRasterPos3sv, (const GLshort *v));
TSGL_CORE_PROC(void, glRasterPos4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TSGL_CORE_PROC(void, glRasterPos4dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glRasterPos4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TSGL_CORE_PROC(void, glRasterPos4fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glRasterPos4i, (GLint x, GLint y, GLint z, GLint w));
TSGL_CORE_PROC(void, glRasterPos4iv, (const GLint *v));
TSGL_CORE_PROC(void, glRasterPos4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TSGL_CORE_PROC(void, glRasterPos4sv, (const GLshort *v));
TSGL_CORE_PROC(void, glReadBuffer, (GLenum mode));
TSGL_CORE_PROC(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels));
TSGL_CORE_PROC(void, glRectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2));
TSGL_CORE_PROC(void, glRectdv, (const GLdouble *v1, const GLdouble *v2));
TSGL_CORE_PROC(void, glRectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2));
TSGL_CORE_PROC(void, glRectfv, (const GLfloat *v1, const GLfloat *v2));
TSGL_CORE_PROC(void, glRecti, (GLint x1, GLint y1, GLint x2, GLint y2));
TSGL_CORE_PROC(void, glRectiv, (const GLint *v1, const GLint *v2));
TSGL_CORE_PROC(void, glRects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2));
TSGL_CORE_PROC(void, glRectsv, (const GLshort *v1, const GLshort *v2));
TSGL_CORE_PROC(GLint, glRenderMode, (GLenum mode));
TSGL_CORE_PROC(void, glRotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z));
TSGL_CORE_PROC(void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void, glScaled, (GLdouble x, GLdouble y, GLdouble z));
TSGL_CORE_PROC(void, glScalef, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void, glSelectBuffer, (GLsizei size, GLuint *buffer));
TSGL_CORE_PROC(void, glShadeModel, (GLenum mode));
TSGL_CORE_PROC(void, glStencilFunc, (GLenum func, GLint ref, GLuint mask));
TSGL_CORE_PROC(void, glStencilMask, (GLuint mask));
TSGL_CORE_PROC(void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
TSGL_CORE_PROC(void, glTexCoord1d, (GLdouble s));
TSGL_CORE_PROC(void, glTexCoord1dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glTexCoord1f, (GLfloat s));
TSGL_CORE_PROC(void, glTexCoord1fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glTexCoord1i, (GLint s));
TSGL_CORE_PROC(void, glTexCoord1iv, (const GLint *v));
TSGL_CORE_PROC(void, glTexCoord1s, (GLshort s));
TSGL_CORE_PROC(void, glTexCoord1sv, (const GLshort *v));
TSGL_CORE_PROC(void, glTexCoord2d, (GLdouble s, GLdouble t));
TSGL_CORE_PROC(void, glTexCoord2dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glTexCoord2f, (GLfloat s, GLfloat t));
TSGL_CORE_PROC(void, glTexCoord2fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glTexCoord2i, (GLint s, GLint t));
TSGL_CORE_PROC(void, glTexCoord2iv, (const GLint *v));
TSGL_CORE_PROC(void, glTexCoord2s, (GLshort s, GLshort t));
TSGL_CORE_PROC(void, glTexCoord2sv, (const GLshort *v));
TSGL_CORE_PROC(void, glTexCoord3d, (GLdouble s, GLdouble t, GLdouble r));
TSGL_CORE_PROC(void, glTexCoord3dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glTexCoord3f, (GLfloat s, GLfloat t, GLfloat r));
TSGL_CORE_PROC(void, glTexCoord3fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glTexCoord3i, (GLint s, GLint t, GLint r));
TSGL_CORE_PROC(void, glTexCoord3iv, (const GLint *v));
TSGL_CORE_PROC(void, glTexCoord3s, (GLshort s, GLshort t, GLshort r));
TSGL_CORE_PROC(void, glTexCoord3sv, (const GLshort *v));
TSGL_CORE_PROC(void, glTexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q));
TSGL_CORE_PROC(void, glTexCoord4dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glTexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q));
TSGL_CORE_PROC(void, glTexCoord4fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glTexCoord4i, (GLint s, GLint t, GLint r, GLint q));
TSGL_CORE_PROC(void, glTexCoord4iv, (const GLint *v));
TSGL_CORE_PROC(void, glTexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q));
TSGL_CORE_PROC(void, glTexCoord4sv, (const GLshort *v));
TSGL_CORE_PROC(void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glTexEnvi, (GLenum target, GLenum pname, GLint param));
TSGL_CORE_PROC(void, glTexEnviv, (GLenum target, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glTexGend, (GLenum coord, GLenum pname, GLdouble param));
TSGL_CORE_PROC(void, glTexGendv, (GLenum coord, GLenum pname, const GLdouble *params));
TSGL_CORE_PROC(void, glTexGenf, (GLenum coord, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glTexGenfv, (GLenum coord, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glTexGeni, (GLenum coord, GLenum pname, GLint param));
TSGL_CORE_PROC(void, glTexGeniv, (GLenum coord, GLenum pname, const GLint *params));
#  if defined __SH4__
TSGL_CORE_PROC(void, glTexImage1D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void, glTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
#  else
TSGL_CORE_PROC(void, glTexImage1D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
#  endif
TSGL_CORE_PROC(void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void, glTexParameteri, (GLenum target, GLenum pname, GLint param));
TSGL_CORE_PROC(void, glTexParameteriv, (GLenum target, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void, glTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void, glTranslated, (GLdouble x, GLdouble y, GLdouble z));
TSGL_CORE_PROC(void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void, glVertex2d, (GLdouble x, GLdouble y));
TSGL_CORE_PROC(void, glVertex2dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glVertex2f, (GLfloat x, GLfloat y));
TSGL_CORE_PROC(void, glVertex2fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glVertex2i, (GLint x, GLint y));
TSGL_CORE_PROC(void, glVertex2iv, (const GLint *v));
TSGL_CORE_PROC(void, glVertex2s, (GLshort x, GLshort y));
TSGL_CORE_PROC(void, glVertex2sv, (const GLshort *v));
TSGL_CORE_PROC(void, glVertex3d, (GLdouble x, GLdouble y, GLdouble z));
TSGL_CORE_PROC(void, glVertex3dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glVertex3f, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void, glVertex3fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glVertex3i, (GLint x, GLint y, GLint z));
TSGL_CORE_PROC(void, glVertex3iv, (const GLint *v));
TSGL_CORE_PROC(void, glVertex3s, (GLshort x, GLshort y, GLshort z));
TSGL_CORE_PROC(void, glVertex3sv, (const GLshort *v));
TSGL_CORE_PROC(void, glVertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
TSGL_CORE_PROC(void, glVertex4dv, (const GLdouble *v));
TSGL_CORE_PROC(void, glVertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
TSGL_CORE_PROC(void, glVertex4fv, (const GLfloat *v));
TSGL_CORE_PROC(void, glVertex4i, (GLint x, GLint y, GLint z, GLint w));
TSGL_CORE_PROC(void, glVertex4iv, (const GLint *v));
TSGL_CORE_PROC(void, glVertex4s, (GLshort x, GLshort y, GLshort z, GLshort w));
TSGL_CORE_PROC(void, glVertex4sv, (const GLshort *v));
TSGL_CORE_PROC(void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));
