TSGL_CORE_PROC(void,glActiveTexture, (GLenum texture));
TSGL_CORE_PROC(void,glAlphaFunc, (GLenum func, GLclampf ref));
TSGL_CORE_PROC(void,glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
TSGL_CORE_PROC(void,glClearDepthf, (GLclampf depth));
TSGL_CORE_PROC(void,glClipPlanef, (GLenum plane, const GLfloat *equation));
TSGL_CORE_PROC(void,glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
TSGL_CORE_PROC(void,glDepthRangef, (GLclampf zNear, GLclampf zFar));
TSGL_CORE_PROC(void,glFogf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glFogfv, (GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glFrustumf, (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar));
TSGL_CORE_PROC(void,glGetClipPlanef, (GLenum pname, GLfloat eqn[4]));
TSGL_CORE_PROC(void,glGetFloatv, (GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void,glGetLightfv, (GLenum light, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void,glGetMaterialfv, (GLenum face, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void,glGetTexEnvfv, (GLenum env, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void,glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat *params));
TSGL_CORE_PROC(void,glLightModelf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glLightModelfv, (GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glLightf, (GLenum light, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glLightfv, (GLenum light, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glLineWidth, (GLfloat width));
TSGL_CORE_PROC(void,glLoadMatrixf, (const GLfloat *m));
TSGL_CORE_PROC(void,glMaterialf, (GLenum face, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glMaterialfv, (GLenum face, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glMultMatrixf, (const GLfloat *m));
TSGL_CORE_PROC(void,glMultiTexCoord4f, (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q));
TSGL_CORE_PROC(void,glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz));
TSGL_CORE_PROC(void,glOrthof, (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar));
TSGL_CORE_PROC(void,glPointParameterf, (GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glPointParameterfv, (GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glPointSize, (GLfloat size));
TSGL_CORE_PROC(void,glPolygonOffset, (GLfloat factor, GLfloat units));
TSGL_CORE_PROC(void,glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void,glScalef, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void,glTexEnvf, (GLenum target, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glTexEnvfv, (GLenum target, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
TSGL_CORE_PROC(void,glTexParameterfv, (GLenum target, GLenum pname, const GLfloat *params));
TSGL_CORE_PROC(void,glTranslatef, (GLfloat x, GLfloat y, GLfloat z));
TSGL_CORE_PROC(void,glAlphaFuncx, (GLenum func, GLclampx ref));
TSGL_CORE_PROC(void,glBindBuffer, (GLenum target, GLuint buffer));
TSGL_CORE_PROC(void,glBindTexture, (GLenum target, GLuint texture));
TSGL_CORE_PROC(void,glBlendFunc, (GLenum sfactor, GLenum dfactor));
TSGL_CORE_PROC(void,glBufferData, (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage));
TSGL_CORE_PROC(void,glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data));
TSGL_CORE_PROC(void,glClear, (GLbitfield mask));
TSGL_CORE_PROC(void,glClearColorx, (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha));
TSGL_CORE_PROC(void,glClearDepthx, (GLclampx depth));
TSGL_CORE_PROC(void,glClearStencil, (GLint s));
TSGL_CORE_PROC(void,glClientActiveTexture, (GLenum texture));
TSGL_CORE_PROC(void,glClipPlanex, (GLenum plane, const GLfixed *equation));
TSGL_CORE_PROC(void,glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
TSGL_CORE_PROC(void,glColor4x, (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha));
TSGL_CORE_PROC(void,glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
TSGL_CORE_PROC(void,glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void,glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data));
TSGL_CORE_PROC(void,glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data));
TSGL_CORE_PROC(void,glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
TSGL_CORE_PROC(void,glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void,glCullFace, (GLenum mode));
TSGL_CORE_PROC(void,glDeleteBuffers, (GLsizei n, const GLuint *buffers));
TSGL_CORE_PROC(void,glDeleteTextures, (GLsizei n, const GLuint *textures));
TSGL_CORE_PROC(void,glDepthFunc, (GLenum func));
TSGL_CORE_PROC(void,glDepthMask, (GLboolean flag));
TSGL_CORE_PROC(void,glDepthRangex, (GLclampx zNear, GLclampx zFar));
TSGL_CORE_PROC(void,glDisable, (GLenum cap));
TSGL_CORE_PROC(void,glDisableClientState, (GLenum array));
TSGL_CORE_PROC(void,glDrawArrays, (GLenum mode, GLint first, GLsizei count));
TSGL_CORE_PROC(void,glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices));
TSGL_CORE_PROC(void,glEnable, (GLenum cap));
TSGL_CORE_PROC(void,glEnableClientState, (GLenum array));
TSGL_CORE_PROC(void,glFinish, (void));
TSGL_CORE_PROC(void,glFlush, (void));
TSGL_CORE_PROC(void,glFogx, (GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glFogxv, (GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glFrontFace, (GLenum mode));
TSGL_CORE_PROC(void,glFrustumx, (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar));
TSGL_CORE_PROC(void,glGetBooleanv, (GLenum pname, GLboolean *params));
TSGL_CORE_PROC(void,glGetBufferParameteriv, (GLenum target, GLenum pname, GLint *params));
TSGL_CORE_PROC(void,glGetClipPlanex, (GLenum pname, GLfixed eqn[4]));
TSGL_CORE_PROC(void,glGenBuffers, (GLsizei n, GLuint *buffers));
TSGL_CORE_PROC(void,glGenTextures, (GLsizei n, GLuint *textures));
TSGL_CORE_PROC(GLenum,glGetError, (void));
TSGL_CORE_PROC(void,glGetFixedv, (GLenum pname, GLfixed *params));
TSGL_CORE_PROC(void,glGetIntegerv, (GLenum pname, GLint *params));
TSGL_CORE_PROC(void,glGetLightxv, (GLenum light, GLenum pname, GLfixed *params));
TSGL_CORE_PROC(void,glGetMaterialxv, (GLenum face, GLenum pname, GLfixed *params));
TSGL_CORE_PROC(void,glGetPointerv, (GLenum pname, void **params));
TSGL_CORE_PROC(const GLubyte *,glGetString, (GLenum name));
TSGL_CORE_PROC(void,glGetTexEnviv, (GLenum env, GLenum pname, GLint *params));
TSGL_CORE_PROC(void,glGetTexEnvxv, (GLenum env, GLenum pname, GLfixed *params));
TSGL_CORE_PROC(void,glGetTexParameteriv, (GLenum target, GLenum pname, GLint *params));
TSGL_CORE_PROC(void,glGetTexParameterxv, (GLenum target, GLenum pname, GLfixed *params));
TSGL_CORE_PROC(void,glHint, (GLenum target, GLenum mode));
TSGL_CORE_PROC(GLboolean,glIsBuffer, (GLuint buffer));
TSGL_CORE_PROC(GLboolean,glIsEnabled, (GLenum cap));
TSGL_CORE_PROC(GLboolean,glIsTexture, (GLuint texture));
TSGL_CORE_PROC(void,glLightModelx, (GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glLightModelxv, (GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glLightx, (GLenum light, GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glLightxv, (GLenum light, GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glLineWidthx, (GLfixed width));
TSGL_CORE_PROC(void,glLoadIdentity, (void));
TSGL_CORE_PROC(void,glLoadMatrixx, (const GLfixed *m));
TSGL_CORE_PROC(void,glLogicOp, (GLenum opcode));
TSGL_CORE_PROC(void,glMaterialx, (GLenum face, GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glMaterialxv, (GLenum face, GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glMatrixMode, (GLenum mode));
TSGL_CORE_PROC(void,glMultMatrixx, (const GLfixed *m));
TSGL_CORE_PROC(void,glMultiTexCoord4x, (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q));
TSGL_CORE_PROC(void,glNormal3x, (GLfixed nx, GLfixed ny, GLfixed nz));
TSGL_CORE_PROC(void,glNormalPointer, (GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void,glOrthox, (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar));
TSGL_CORE_PROC(void,glPixelStorei, (GLenum pname, GLint param));
TSGL_CORE_PROC(void,glPointParameterx, (GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glPointParameterxv, (GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glPointSizex, (GLfixed size));
TSGL_CORE_PROC(void,glPolygonOffsetx, (GLfixed factor, GLfixed units));
TSGL_CORE_PROC(void,glPopMatrix, (void));
TSGL_CORE_PROC(void,glPushMatrix, (void));
TSGL_CORE_PROC(void,glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels));
TSGL_CORE_PROC(void,glRotatex, (GLfixed angle, GLfixed x, GLfixed y, GLfixed z));
TSGL_CORE_PROC(void,glSampleCoverage, (GLclampf value, GLboolean invert));
TSGL_CORE_PROC(void,glSampleCoveragex, (GLclampx value, GLboolean invert));
TSGL_CORE_PROC(void,glScalex, (GLfixed x, GLfixed y, GLfixed z));
TSGL_CORE_PROC(void,glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void,glShadeModel, (GLenum mode));
TSGL_CORE_PROC(void,glStencilFunc, (GLenum func, GLint ref, GLuint mask));
TSGL_CORE_PROC(void,glStencilMask, (GLuint mask));
TSGL_CORE_PROC(void,glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
TSGL_CORE_PROC(void,glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void,glTexEnvi, (GLenum target, GLenum pname, GLint param));
TSGL_CORE_PROC(void,glTexEnvx, (GLenum target, GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glTexEnviv, (GLenum target, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void,glTexEnvxv, (GLenum target, GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void,glTexParameteri, (GLenum target, GLenum pname, GLint param));
TSGL_CORE_PROC(void,glTexParameterx, (GLenum target, GLenum pname, GLfixed param));
TSGL_CORE_PROC(void,glTexParameteriv, (GLenum target, GLenum pname, const GLint *params));
TSGL_CORE_PROC(void,glTexParameterxv, (GLenum target, GLenum pname, const GLfixed *params));
TSGL_CORE_PROC(void,glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels));
TSGL_CORE_PROC(void,glTranslatex, (GLfixed x, GLfixed y, GLfixed z));
TSGL_CORE_PROC(void,glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
TSGL_CORE_PROC(void,glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));
TSGL_CORE_PROC(void,glPointSizePointerOES, (GLenum type, GLsizei stride, const GLvoid *pointer));
