//////////////////////////////////////////////////////////////////////////////////////////////
//
// Autogenerated module definition, for ni::niTestInterop.
//
//////////////////////////////////////////////////////////////////////////////////////////////
//lint -e750 : local macro '_XXX_ModuleDef' (line NN, file _XXX_ModuleDef.cpp) not referenced
//lint -e766 : Header file '...\ModuleDefImpl_Begin.h' not used in module '_XXX_ModuleDef.cpp'

#include "stdafx.h"
#include "API/niTestInterop_ModuleDef.h"
#include <niLang/Utils/ModuleDefImpl_Begin.h>

#ifndef niConfig_OnlyObjectTypesIDL
#endif // #ifndef niConfig_OnlyObjectTypesIDL



#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef
#define _niTestInterop_ModuleDef
#include <niLang/Utils/VMCallCImpl.h>
#ifndef niConfig_NoXCALL
#define IDLC_BEGIN_NAMESPACE() namespace ni { namespace xcall_cimpl {
#define IDLC_END_NAMESPACE() }}
#ifndef XCALL_CIMPL
#define XCALL_CIMPL(NAME) ni::xcall_cimpl::NAME
#endif
#include "_idl/ITestInterop.h.idl.inl"
#endif // niConfig_NoXCALL
#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef

namespace ni {
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef


//////////////////////////////////////////////////////////////////////////////////////////////
// iTestInteropObject wrapper
//////////////////////////////////////////////////////////////////////////////////////////////
niExportFunc(const ni::sInterfaceDef*) GetInterfaceDef_iTestInteropObject() {

// Method: SetNumItems
static const ni::sParameterDef iTestInteropObject_SetNumItems_Parameters[1] = { 
  { "aNumItems", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_SetNumItems = {
  "SetNumItems",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Size, NULL, "void",
  1, iTestInteropObject_SetNumItems_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetNumItems)
#else
  NULL
#endif
};

// Method: GetNumItems
static const ni::sMethodDef iTestInteropObject_GetNumItems = {
  "GetNumItems",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Size, NULL, "tSize",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetNumItems)
#else
  NULL
#endif
};

// Method: SetTestInterop
static const ni::sParameterDef iTestInteropObject_SetTestInterop_Parameters[1] = { 
  { "apStruct", ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "sTestInterop*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetTestInterop = {
  "SetTestInterop",
  0|ni::eType_Null, NULL, "void",
  1, iTestInteropObject_SetTestInterop_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetTestInterop)
#else
  NULL
#endif
};

// Method: GetTestInterop
static const ni::sMethodDef iTestInteropObject_GetTestInterop = {
  "GetTestInterop",
  0|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "sTestInterop*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetTestInterop)
#else
  NULL
#endif
};

// Method: SetTestInteropConst
static const ni::sParameterDef iTestInteropObject_SetTestInteropConst_Parameters[1] = { 
  { "apStruct", ni::eTypeFlags_Constant|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "const sTestInterop*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetTestInteropConst = {
  "SetTestInteropConst",
  0|ni::eType_Null, NULL, "void",
  1, iTestInteropObject_SetTestInteropConst_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetTestInteropConst)
#else
  NULL
#endif
};

// Method: GetTestInteropConst
static const ni::sMethodDef iTestInteropObject_GetTestInteropConst = {
  "GetTestInteropConst",
  0|ni::eTypeFlags_Constant|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "const sTestInterop*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetTestInteropConst)
#else
  NULL
#endif
};

// Method: SetTestInteropRef
static const ni::sParameterDef iTestInteropObject_SetTestInteropRef_Parameters[1] = { 
  { "aStruct", ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "sTestInterop&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetTestInteropRef = {
  "SetTestInteropRef",
  0|ni::eType_Null, NULL, "void",
  1, iTestInteropObject_SetTestInteropRef_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetTestInteropRef)
#else
  NULL
#endif
};

// Method: GetTestInteropRef
static const ni::sMethodDef iTestInteropObject_GetTestInteropRef = {
  "GetTestInteropRef",
  0|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "sTestInterop&",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetTestInteropRef)
#else
  NULL
#endif
};

// Method: SetTestInteropConstRef
static const ni::sParameterDef iTestInteropObject_SetTestInteropConstRef_Parameters[1] = { 
  { "aStruct", ni::eTypeFlags_Constant|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "const sTestInterop&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetTestInteropConstRef = {
  "SetTestInteropConstRef",
  0|ni::eType_Null, NULL, "void",
  1, iTestInteropObject_SetTestInteropConstRef_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetTestInteropConstRef)
#else
  NULL
#endif
};

// Method: GetTestInteropConstRef
static const ni::sMethodDef iTestInteropObject_GetTestInteropConstRef = {
  "GetTestInteropConstRef",
  0|ni::eTypeFlags_Constant|ni::eType_Int|ni::eTypeFlags_Pointer, NULL, "const sTestInterop&",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetTestInteropConstRef)
#else
  NULL
#endif
};

// Method: SetEnum
static const ni::sParameterDef iTestInteropObject_SetEnum_Parameters[1] = { 
  { "aV", ni::eType_Enum, NULL, "eTestInterop" }
}; 
static const ni::sMethodDef iTestInteropObject_SetEnum = {
  "SetEnum",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Enum, NULL, "void",
  1, iTestInteropObject_SetEnum_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetEnum)
#else
  NULL
#endif
};

// Method: GetEnum
static const ni::sMethodDef iTestInteropObject_GetEnum = {
  "GetEnum",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Enum, NULL, "eTestInterop",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetEnum)
#else
  NULL
#endif
};

// Method: SetFlags
static const ni::sParameterDef iTestInteropObject_SetFlags_Parameters[1] = { 
  { "aV", ni::eType_Enum, NULL, "tTestInteropFlags" }
}; 
static const ni::sMethodDef iTestInteropObject_SetFlags = {
  "SetFlags",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Enum, NULL, "void",
  1, iTestInteropObject_SetFlags_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetFlags)
#else
  NULL
#endif
};

// Method: GetFlags
static const ni::sMethodDef iTestInteropObject_GetFlags = {
  "GetFlags",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Enum, NULL, "tTestInteropFlags",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetFlags)
#else
  NULL
#endif
};

// Method: SetIntPtr
static const ni::sParameterDef iTestInteropObject_SetIntPtr_Parameters[1] = { 
  { "aV", ni::eType_IntPtr, NULL, "tIntPtr" }
}; 
static const ni::sMethodDef iTestInteropObject_SetIntPtr = {
  "SetIntPtr",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IntPtr, NULL, "void",
  1, iTestInteropObject_SetIntPtr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetIntPtr)
#else
  NULL
#endif
};

// Method: GetIntPtr
static const ni::sMethodDef iTestInteropObject_GetIntPtr = {
  "GetIntPtr",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IntPtr, NULL, "tIntPtr",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetIntPtr)
#else
  NULL
#endif
};

// Method: SetUIntPtr
static const ni::sParameterDef iTestInteropObject_SetUIntPtr_Parameters[1] = { 
  { "aV", ni::eType_IntPtr, NULL, "tIntPtr" }
}; 
static const ni::sMethodDef iTestInteropObject_SetUIntPtr = {
  "SetUIntPtr",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IntPtr, NULL, "void",
  1, iTestInteropObject_SetUIntPtr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetUIntPtr)
#else
  NULL
#endif
};

// Method: GetUIntPtr
static const ni::sMethodDef iTestInteropObject_GetUIntPtr = {
  "GetUIntPtr",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IntPtr, NULL, "tIntPtr",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetUIntPtr)
#else
  NULL
#endif
};

// Method: SetI8
static const ni::sParameterDef iTestInteropObject_SetI8_Parameters[1] = { 
  { "aV", ni::eType_I8, NULL, "tI8" }
}; 
static const ni::sMethodDef iTestInteropObject_SetI8 = {
  "SetI8",
  ni::eTypeFlags_MethodSetter|0|ni::eType_I8, NULL, "void",
  1, iTestInteropObject_SetI8_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetI8)
#else
  NULL
#endif
};

// Method: GetI8
static const ni::sMethodDef iTestInteropObject_GetI8 = {
  "GetI8",
  ni::eTypeFlags_MethodGetter|0|ni::eType_I8, NULL, "tI8",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetI8)
#else
  NULL
#endif
};

// Method: SetU8
static const ni::sParameterDef iTestInteropObject_SetU8_Parameters[1] = { 
  { "aV", ni::eType_U8, NULL, "tU8" }
}; 
static const ni::sMethodDef iTestInteropObject_SetU8 = {
  "SetU8",
  ni::eTypeFlags_MethodSetter|0|ni::eType_U8, NULL, "void",
  1, iTestInteropObject_SetU8_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetU8)
#else
  NULL
#endif
};

// Method: GetU8
static const ni::sMethodDef iTestInteropObject_GetU8 = {
  "GetU8",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U8, NULL, "tU8",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetU8)
#else
  NULL
#endif
};

// Method: SetI16
static const ni::sParameterDef iTestInteropObject_SetI16_Parameters[1] = { 
  { "aV", ni::eType_I16, NULL, "tI16" }
}; 
static const ni::sMethodDef iTestInteropObject_SetI16 = {
  "SetI16",
  ni::eTypeFlags_MethodSetter|0|ni::eType_I16, NULL, "void",
  1, iTestInteropObject_SetI16_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetI16)
#else
  NULL
#endif
};

// Method: GetI16
static const ni::sMethodDef iTestInteropObject_GetI16 = {
  "GetI16",
  ni::eTypeFlags_MethodGetter|0|ni::eType_I16, NULL, "tI16",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetI16)
#else
  NULL
#endif
};

// Method: SetU16
static const ni::sParameterDef iTestInteropObject_SetU16_Parameters[1] = { 
  { "aV", ni::eType_U16, NULL, "tU16" }
}; 
static const ni::sMethodDef iTestInteropObject_SetU16 = {
  "SetU16",
  ni::eTypeFlags_MethodSetter|0|ni::eType_U16, NULL, "void",
  1, iTestInteropObject_SetU16_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetU16)
#else
  NULL
#endif
};

// Method: GetU16
static const ni::sMethodDef iTestInteropObject_GetU16 = {
  "GetU16",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U16, NULL, "tU16",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetU16)
#else
  NULL
#endif
};

// Method: SetI32
static const ni::sParameterDef iTestInteropObject_SetI32_Parameters[1] = { 
  { "aV", ni::eType_I32, NULL, "tI32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetI32 = {
  "SetI32",
  ni::eTypeFlags_MethodSetter|0|ni::eType_I32, NULL, "void",
  1, iTestInteropObject_SetI32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetI32)
#else
  NULL
#endif
};

// Method: GetI32
static const ni::sMethodDef iTestInteropObject_GetI32 = {
  "GetI32",
  ni::eTypeFlags_MethodGetter|0|ni::eType_I32, NULL, "tI32",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetI32)
#else
  NULL
#endif
};

// Method: SetU32
static const ni::sParameterDef iTestInteropObject_SetU32_Parameters[1] = { 
  { "aV", ni::eType_U32, NULL, "tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetU32 = {
  "SetU32",
  ni::eTypeFlags_MethodSetter|0|ni::eType_U32, NULL, "void",
  1, iTestInteropObject_SetU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetU32)
#else
  NULL
#endif
};

// Method: GetU32
static const ni::sMethodDef iTestInteropObject_GetU32 = {
  "GetU32",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U32, NULL, "tU32",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetU32)
#else
  NULL
#endif
};

// Method: SetI64
static const ni::sParameterDef iTestInteropObject_SetI64_Parameters[1] = { 
  { "aV", ni::eType_I64, NULL, "tI64" }
}; 
static const ni::sMethodDef iTestInteropObject_SetI64 = {
  "SetI64",
  ni::eTypeFlags_MethodSetter|0|ni::eType_I64, NULL, "void",
  1, iTestInteropObject_SetI64_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetI64)
#else
  NULL
#endif
};

// Method: GetI64
static const ni::sMethodDef iTestInteropObject_GetI64 = {
  "GetI64",
  ni::eTypeFlags_MethodGetter|0|ni::eType_I64, NULL, "tI64",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetI64)
#else
  NULL
#endif
};

// Method: SetU64
static const ni::sParameterDef iTestInteropObject_SetU64_Parameters[1] = { 
  { "aV", ni::eType_U64, NULL, "tU64" }
}; 
static const ni::sMethodDef iTestInteropObject_SetU64 = {
  "SetU64",
  ni::eTypeFlags_MethodSetter|0|ni::eType_U64, NULL, "void",
  1, iTestInteropObject_SetU64_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetU64)
#else
  NULL
#endif
};

// Method: GetU64
static const ni::sMethodDef iTestInteropObject_GetU64 = {
  "GetU64",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U64, NULL, "tU64",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetU64)
#else
  NULL
#endif
};

// Method: SetF32
static const ni::sParameterDef iTestInteropObject_SetF32_Parameters[1] = { 
  { "aV", ni::eType_F32, NULL, "tF32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetF32 = {
  "SetF32",
  ni::eTypeFlags_MethodSetter|0|ni::eType_F32, NULL, "void",
  1, iTestInteropObject_SetF32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetF32)
#else
  NULL
#endif
};

// Method: GetF32
static const ni::sMethodDef iTestInteropObject_GetF32 = {
  "GetF32",
  ni::eTypeFlags_MethodGetter|0|ni::eType_F32, NULL, "tF32",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetF32)
#else
  NULL
#endif
};

// Method: SetF64
static const ni::sParameterDef iTestInteropObject_SetF64_Parameters[1] = { 
  { "aV", ni::eType_F64, NULL, "tF64" }
}; 
static const ni::sMethodDef iTestInteropObject_SetF64 = {
  "SetF64",
  ni::eTypeFlags_MethodSetter|0|ni::eType_F64, NULL, "void",
  1, iTestInteropObject_SetF64_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetF64)
#else
  NULL
#endif
};

// Method: GetF64
static const ni::sMethodDef iTestInteropObject_GetF64 = {
  "GetF64",
  ni::eTypeFlags_MethodGetter|0|ni::eType_F64, NULL, "tF64",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetF64)
#else
  NULL
#endif
};

// Method: SetVar
static const ni::sParameterDef iTestInteropObject_SetVar_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Variant|ni::eTypeFlags_Pointer, NULL, "const Var&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVar = {
  "SetVar",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Variant|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVar_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVar)
#else
  NULL
#endif
};

// Method: GetVar
static const ni::sMethodDef iTestInteropObject_GetVar = {
  "GetVar",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Variant, NULL, "Var",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVar)
#else
  NULL
#endif
};

// Method: SetVec2l
static const ni::sParameterDef iTestInteropObject_SetVec2l_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec2i|ni::eTypeFlags_Pointer, NULL, "const sVec2i&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec2l = {
  "SetVec2l",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec2i|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec2l_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec2l)
#else
  NULL
#endif
};

// Method: GetVec2l
static const ni::sMethodDef iTestInteropObject_GetVec2l = {
  "GetVec2l",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec2i, NULL, "sVec2i",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec2l)
#else
  NULL
#endif
};

// Method: SetVec2f
static const ni::sParameterDef iTestInteropObject_SetVec2f_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec2f|ni::eTypeFlags_Pointer, NULL, "const sVec2f&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec2f = {
  "SetVec2f",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec2f|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec2f_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec2f)
#else
  NULL
#endif
};

// Method: GetVec2f
static const ni::sMethodDef iTestInteropObject_GetVec2f = {
  "GetVec2f",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec2f, NULL, "sVec2f",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec2f)
#else
  NULL
#endif
};

// Method: SetVec3l
static const ni::sParameterDef iTestInteropObject_SetVec3l_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec3i|ni::eTypeFlags_Pointer, NULL, "const sVec3i&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec3l = {
  "SetVec3l",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec3i|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec3l_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec3l)
#else
  NULL
#endif
};

// Method: GetVec3l
static const ni::sMethodDef iTestInteropObject_GetVec3l = {
  "GetVec3l",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec3i, NULL, "sVec3i",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec3l)
#else
  NULL
#endif
};

// Method: SetVec3f
static const ni::sParameterDef iTestInteropObject_SetVec3f_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec3f|ni::eTypeFlags_Pointer, NULL, "const sVec3f&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec3f = {
  "SetVec3f",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec3f|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec3f_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec3f)
#else
  NULL
#endif
};

// Method: GetVec3f
static const ni::sMethodDef iTestInteropObject_GetVec3f = {
  "GetVec3f",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec3f, NULL, "sVec3f",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec3f)
#else
  NULL
#endif
};

// Method: SetVec4l
static const ni::sParameterDef iTestInteropObject_SetVec4l_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec4i|ni::eTypeFlags_Pointer, NULL, "const sVec4i&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec4l = {
  "SetVec4l",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec4i|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec4l_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec4l)
#else
  NULL
#endif
};

// Method: GetVec4l
static const ni::sMethodDef iTestInteropObject_GetVec4l = {
  "GetVec4l",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec4i, NULL, "sVec4i",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec4l)
#else
  NULL
#endif
};

// Method: SetVec4f
static const ni::sParameterDef iTestInteropObject_SetVec4f_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Vec4f|ni::eTypeFlags_Pointer, NULL, "const sVec4f&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetVec4f = {
  "SetVec4f",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Vec4f|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetVec4f_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetVec4f)
#else
  NULL
#endif
};

// Method: GetVec4f
static const ni::sMethodDef iTestInteropObject_GetVec4f = {
  "GetVec4f",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Vec4f, NULL, "sVec4f",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetVec4f)
#else
  NULL
#endif
};

// Method: SetMatrixf
static const ni::sParameterDef iTestInteropObject_SetMatrixf_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer, NULL, "const sMatrixf&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetMatrixf = {
  "SetMatrixf",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetMatrixf_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetMatrixf)
#else
  NULL
#endif
};

// Method: GetMatrixf
static const ni::sMethodDef iTestInteropObject_GetMatrixf = {
  "GetMatrixf",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Matrixf, NULL, "sMatrixf",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetMatrixf)
#else
  NULL
#endif
};

// Method: SetMatrixfValues
static const ni::sParameterDef iTestInteropObject_SetMatrixfValues_Parameters[16] = { 
  { "a00", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a01", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a02", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a03", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a10", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a11", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a12", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a13", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a20", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a21", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a22", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a23", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a30", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a31", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a32", ni::eType_F32, NULL, "ni::tF32" }, 
  { "a33", ni::eType_F32, NULL, "ni::tF32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetMatrixfValues = {
  "SetMatrixfValues",
  0|ni::eType_I8, NULL, "ni::tBool",
  16, iTestInteropObject_SetMatrixfValues_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetMatrixfValues)
#else
  NULL
#endif
};

// Method: SetACharStrZ
static const ni::sParameterDef iTestInteropObject_SetACharStrZ_Parameters[1] = { 
  { "aV", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetACharStrZ = {
  "SetACharStrZ",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetACharStrZ_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetACharStrZ)
#else
  NULL
#endif
};

// Method: GetACharStrZ
static const ni::sMethodDef iTestInteropObject_GetACharStrZ = {
  "GetACharStrZ",
  ni::eTypeFlags_MethodGetter|0|ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetACharStrZ)
#else
  NULL
#endif
};

// Method: SetString
static const ni::sParameterDef iTestInteropObject_SetString_Parameters[1] = { 
  { "aStr", ni::eType_String, NULL, "cString" }
}; 
static const ni::sMethodDef iTestInteropObject_SetString = {
  "SetString",
  ni::eTypeFlags_MethodSetter|0|ni::eType_String, NULL, "void",
  1, iTestInteropObject_SetString_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetString)
#else
  NULL
#endif
};

// Method: GetString
static const ni::sMethodDef iTestInteropObject_GetString = {
  "GetString",
  ni::eTypeFlags_MethodGetter|0|ni::eType_String, NULL, "cString",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetString)
#else
  NULL
#endif
};

// Method: SetStringCRef
static const ni::sParameterDef iTestInteropObject_SetStringCRef_Parameters[1] = { 
  { "aStr", ni::eTypeFlags_Constant|ni::eType_String|ni::eTypeFlags_Pointer, NULL, "const cString&" }
}; 
static const ni::sMethodDef iTestInteropObject_SetStringCRef = {
  "SetStringCRef",
  ni::eTypeFlags_MethodSetter|0|ni::eTypeFlags_Constant|ni::eType_String|ni::eTypeFlags_Pointer, NULL, "void",
  1, iTestInteropObject_SetStringCRef_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetStringCRef)
#else
  NULL
#endif
};

// Method: GetStringCRef
static const ni::sMethodDef iTestInteropObject_GetStringCRef = {
  "GetStringCRef",
  ni::eTypeFlags_MethodGetter|0|ni::eTypeFlags_Constant|ni::eType_String|ni::eTypeFlags_Pointer, NULL, "const cString&",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetStringCRef)
#else
  NULL
#endif
};

// Method: SetHString
static const ni::sParameterDef iTestInteropObject_SetHString_Parameters[1] = { 
  { "ahspStr", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iHString), "iHString*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetHString = {
  "SetHString",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iHString), "void",
  1, iTestInteropObject_SetHString_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetHString)
#else
  NULL
#endif
};

// Method: GetHString
static const ni::sMethodDef iTestInteropObject_GetHString = {
  "GetHString",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iHString), "iHString*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetHString)
#else
  NULL
#endif
};

// Method: SetIndexedU32
static const ni::sParameterDef iTestInteropObject_SetIndexedU32_Parameters[2] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }, 
  { "aV", ni::eType_U32, NULL, "tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetIndexedU32 = {
  "SetIndexedU32",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetIndexedU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetIndexedU32)
#else
  NULL
#endif
};

// Method: GetIndexedU32
static const ni::sParameterDef iTestInteropObject_GetIndexedU32_Parameters[1] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_GetIndexedU32 = {
  "GetIndexedU32",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U32, NULL, "tU32",
  1, iTestInteropObject_GetIndexedU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetIndexedU32)
#else
  NULL
#endif
};

// Method: SetMappedU32
static const ni::sParameterDef iTestInteropObject_SetMappedU32_Parameters[2] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }, 
  { "aV", ni::eType_U32, NULL, "tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_SetMappedU32 = {
  "SetMappedU32",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetMappedU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetMappedU32)
#else
  NULL
#endif
};

// Method: GetMappedU32
static const ni::sParameterDef iTestInteropObject_GetMappedU32_Parameters[1] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }
}; 
static const ni::sMethodDef iTestInteropObject_GetMappedU32 = {
  "GetMappedU32",
  ni::eTypeFlags_MethodGetter|0|ni::eType_U32, NULL, "tU32",
  1, iTestInteropObject_GetMappedU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetMappedU32)
#else
  NULL
#endif
};

// Method: SetPtr
static const ni::sParameterDef iTestInteropObject_SetPtr_Parameters[1] = { 
  { "aV", ni::eType_Ptr, NULL, "tPtr" }
}; 
static const ni::sMethodDef iTestInteropObject_SetPtr = {
  "SetPtr",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Ptr, NULL, "void",
  1, iTestInteropObject_SetPtr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetPtr)
#else
  NULL
#endif
};

// Method: GetPtr
static const ni::sMethodDef iTestInteropObject_GetPtr = {
  "GetPtr",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Ptr, NULL, "tPtr",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetPtr)
#else
  NULL
#endif
};

// Method: WriteRawBuffer
static const ni::sParameterDef iTestInteropObject_WriteRawBuffer_Parameters[2] = { 
  { "aData", ni::eTypeFlags_Constant|ni::eType_Ptr, NULL, "const tPtr" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_WriteRawBuffer = {
  "WriteRawBuffer",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_WriteRawBuffer_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_WriteRawBuffer)
#else
  NULL
#endif
};

// Method: ReadRawBuffer
static const ni::sParameterDef iTestInteropObject_ReadRawBuffer_Parameters[2] = { 
  { "aData", ni::eType_Ptr, NULL, "tPtr" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_ReadRawBuffer = {
  "ReadRawBuffer",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_ReadRawBuffer_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_ReadRawBuffer)
#else
  NULL
#endif
};

// Method: WriteRawBufferVoid
static const ni::sParameterDef iTestInteropObject_WriteRawBufferVoid_Parameters[2] = { 
  { "apIn", ni::eTypeFlags_Constant|ni::eType_Null|ni::eTypeFlags_Pointer, NULL, "const void*" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_WriteRawBufferVoid = {
  "WriteRawBufferVoid",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_WriteRawBufferVoid_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_WriteRawBufferVoid)
#else
  NULL
#endif
};

// Method: ReadRawBufferVoid
static const ni::sParameterDef iTestInteropObject_ReadRawBufferVoid_Parameters[2] = { 
  { "apOut", ni::eType_Null|ni::eTypeFlags_Pointer, NULL, "void*" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_ReadRawBufferVoid = {
  "ReadRawBufferVoid",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_ReadRawBufferVoid_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_ReadRawBufferVoid)
#else
  NULL
#endif
};

// Method: WriteRawBufferU32
static const ni::sParameterDef iTestInteropObject_WriteRawBufferU32_Parameters[2] = { 
  { "apIn", ni::eTypeFlags_Constant|ni::eType_U32|ni::eTypeFlags_Pointer, NULL, "const tU32*" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_WriteRawBufferU32 = {
  "WriteRawBufferU32",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_WriteRawBufferU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_WriteRawBufferU32)
#else
  NULL
#endif
};

// Method: ReadRawBufferU32
static const ni::sParameterDef iTestInteropObject_ReadRawBufferU32_Parameters[2] = { 
  { "apOut", ni::eType_U32|ni::eTypeFlags_Pointer, NULL, "tU32*" }, 
  { "anSize", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_ReadRawBufferU32 = {
  "ReadRawBufferU32",
  0|ni::eType_I8, NULL, "ni::tBool",
  2, iTestInteropObject_ReadRawBufferU32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_ReadRawBufferU32)
#else
  NULL
#endif
};

// Method: SetIndexedIUnknown
static const ni::sParameterDef iTestInteropObject_SetIndexedIUnknown_Parameters[2] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }, 
  { "aV", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iUnknown), "ni::iUnknown*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetIndexedIUnknown = {
  "SetIndexedIUnknown",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetIndexedIUnknown_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetIndexedIUnknown)
#else
  NULL
#endif
};

// Method: GetIndexedIUnknown
static const ni::sParameterDef iTestInteropObject_GetIndexedIUnknown_Parameters[1] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_GetIndexedIUnknown = {
  "GetIndexedIUnknown",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iUnknown), "ni::iUnknown*",
  1, iTestInteropObject_GetIndexedIUnknown_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetIndexedIUnknown)
#else
  NULL
#endif
};

// Method: SetMappedIUnknown
static const ni::sParameterDef iTestInteropObject_SetMappedIUnknown_Parameters[2] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }, 
  { "aV", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iUnknown), "ni::iUnknown*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetMappedIUnknown = {
  "SetMappedIUnknown",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetMappedIUnknown_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetMappedIUnknown)
#else
  NULL
#endif
};

// Method: GetMappedIUnknown
static const ni::sParameterDef iTestInteropObject_GetMappedIUnknown_Parameters[1] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }
}; 
static const ni::sMethodDef iTestInteropObject_GetMappedIUnknown = {
  "GetMappedIUnknown",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iUnknown), "ni::iUnknown*",
  1, iTestInteropObject_GetMappedIUnknown_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetMappedIUnknown)
#else
  NULL
#endif
};

// Method: SetTestInteropObject
static const ni::sParameterDef iTestInteropObject_SetTestInteropObject_Parameters[1] = { 
  { "aV", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetTestInteropObject = {
  "SetTestInteropObject",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "void",
  1, iTestInteropObject_SetTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetTestInteropObject)
#else
  NULL
#endif
};

// Method: GetTestInteropObject
static const ni::sMethodDef iTestInteropObject_GetTestInteropObject = {
  "GetTestInteropObject",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetTestInteropObject)
#else
  NULL
#endif
};

// Method: SetIndexedTestInteropObject
static const ni::sParameterDef iTestInteropObject_SetIndexedTestInteropObject_Parameters[2] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }, 
  { "aV", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetIndexedTestInteropObject = {
  "SetIndexedTestInteropObject",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetIndexedTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetIndexedTestInteropObject)
#else
  NULL
#endif
};

// Method: GetIndexedTestInteropObject
static const ni::sParameterDef iTestInteropObject_GetIndexedTestInteropObject_Parameters[1] = { 
  { "aIndex", ni::eType_Size, NULL, "tSize" }
}; 
static const ni::sMethodDef iTestInteropObject_GetIndexedTestInteropObject = {
  "GetIndexedTestInteropObject",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropObject_GetIndexedTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetIndexedTestInteropObject)
#else
  NULL
#endif
};

// Method: SetMappedTestInteropObject
static const ni::sParameterDef iTestInteropObject_SetMappedTestInteropObject_Parameters[2] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }, 
  { "aV", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetMappedTestInteropObject = {
  "SetMappedTestInteropObject",
  ni::eTypeFlags_MethodSetter|0|ni::eType_Null, NULL, "void",
  2, iTestInteropObject_SetMappedTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetMappedTestInteropObject)
#else
  NULL
#endif
};

// Method: GetMappedTestInteropObject
static const ni::sParameterDef iTestInteropObject_GetMappedTestInteropObject_Parameters[1] = { 
  { "aaszKey", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const achar*" }
}; 
static const ni::sMethodDef iTestInteropObject_GetMappedTestInteropObject = {
  "GetMappedTestInteropObject",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropObject_GetMappedTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetMappedTestInteropObject)
#else
  NULL
#endif
};

// Method: SetU32Vec
static const ni::sParameterDef iTestInteropObject_SetU32Vec_Parameters[1] = { 
  { "apVec", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "tU32CVec*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetU32Vec = {
  "SetU32Vec",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "void",
  1, iTestInteropObject_SetU32Vec_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetU32Vec)
#else
  NULL
#endif
};

// Method: GetU32Vec
static const ni::sMethodDef iTestInteropObject_GetU32Vec = {
  "GetU32Vec",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "tU32CVec*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetU32Vec)
#else
  NULL
#endif
};

// Method: SetStringMap
static const ni::sParameterDef iTestInteropObject_SetStringMap_Parameters[1] = { 
  { "apMap", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "tStringCMap*" }
}; 
static const ni::sMethodDef iTestInteropObject_SetStringMap = {
  "SetStringMap",
  ni::eTypeFlags_MethodSetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "void",
  1, iTestInteropObject_SetStringMap_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_SetStringMap)
#else
  NULL
#endif
};

// Method: GetStringMap
static const ni::sMethodDef iTestInteropObject_GetStringMap = {
  "GetStringMap",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(ni::iCollection), "tStringCMap*",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_GetStringMap)
#else
  NULL
#endif
};

// Method: Func32
static const ni::sParameterDef iTestInteropObject_Func32_Parameters[32] = { 
  { "a00", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a01", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a02", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a03", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a10", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a11", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a12", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a13", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a20", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a21", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a22", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a23", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a30", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a31", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a32", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a33", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a40", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a41", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a42", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a43", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a50", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a51", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a52", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a53", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a60", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a61", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a62", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a63", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a70", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a71", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a72", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a73", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_Func32 = {
  "Func32",
  0|ni::eType_I8, NULL, "ni::tBool",
  32, iTestInteropObject_Func32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_Func32)
#else
  NULL
#endif
};

// Method: Func33
static const ni::sParameterDef iTestInteropObject_Func33_Parameters[33] = { 
  { "a00", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a01", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a02", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a03", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a10", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a11", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a12", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a13", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a20", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a21", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a22", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a23", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a30", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a31", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a32", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a33", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a40", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a41", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a42", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a43", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a50", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a51", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a52", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a53", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a60", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a61", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a62", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a63", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a70", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a71", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a72", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a73", ni::eType_U32, NULL, "ni::tU32" }, 
  { "firstOops", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_Func33 = {
  "Func33",
  0|ni::eType_I8, NULL, "ni::tBool",
  33, iTestInteropObject_Func33_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_Func33)
#else
  NULL
#endif
};

// Method: Func48
static const ni::sParameterDef iTestInteropObject_Func48_Parameters[40] = { 
  { "a00", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a01", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a02", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a03", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a10", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a11", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a12", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a13", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a20", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a21", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a22", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a23", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a30", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a31", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a32", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a33", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a40", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a41", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a42", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a43", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a50", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a51", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a52", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a53", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a60", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a61", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a62", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a63", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a70", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a71", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a72", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a73", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a80", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a81", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a82", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a83", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a90", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a91", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a92", ni::eType_U32, NULL, "ni::tU32" }, 
  { "a93", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInteropObject_Func48 = {
  "Func48",
  0|ni::eType_I8, NULL, "ni::tBool",
  40, iTestInteropObject_Func48_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropObject_Func48)
#else
  NULL
#endif
};

static const ni::sMethodDef* Methods_iTestInteropObject[] = {
	&iTestInteropObject_SetNumItems,
	&iTestInteropObject_GetNumItems,
	&iTestInteropObject_SetTestInterop,
	&iTestInteropObject_GetTestInterop,
	&iTestInteropObject_SetTestInteropConst,
	&iTestInteropObject_GetTestInteropConst,
	&iTestInteropObject_SetTestInteropRef,
	&iTestInteropObject_GetTestInteropRef,
	&iTestInteropObject_SetTestInteropConstRef,
	&iTestInteropObject_GetTestInteropConstRef,
	&iTestInteropObject_SetEnum,
	&iTestInteropObject_GetEnum,
	&iTestInteropObject_SetFlags,
	&iTestInteropObject_GetFlags,
	&iTestInteropObject_SetIntPtr,
	&iTestInteropObject_GetIntPtr,
	&iTestInteropObject_SetUIntPtr,
	&iTestInteropObject_GetUIntPtr,
	&iTestInteropObject_SetI8,
	&iTestInteropObject_GetI8,
	&iTestInteropObject_SetU8,
	&iTestInteropObject_GetU8,
	&iTestInteropObject_SetI16,
	&iTestInteropObject_GetI16,
	&iTestInteropObject_SetU16,
	&iTestInteropObject_GetU16,
	&iTestInteropObject_SetI32,
	&iTestInteropObject_GetI32,
	&iTestInteropObject_SetU32,
	&iTestInteropObject_GetU32,
	&iTestInteropObject_SetI64,
	&iTestInteropObject_GetI64,
	&iTestInteropObject_SetU64,
	&iTestInteropObject_GetU64,
	&iTestInteropObject_SetF32,
	&iTestInteropObject_GetF32,
	&iTestInteropObject_SetF64,
	&iTestInteropObject_GetF64,
	&iTestInteropObject_SetVar,
	&iTestInteropObject_GetVar,
	&iTestInteropObject_SetVec2l,
	&iTestInteropObject_GetVec2l,
	&iTestInteropObject_SetVec2f,
	&iTestInteropObject_GetVec2f,
	&iTestInteropObject_SetVec3l,
	&iTestInteropObject_GetVec3l,
	&iTestInteropObject_SetVec3f,
	&iTestInteropObject_GetVec3f,
	&iTestInteropObject_SetVec4l,
	&iTestInteropObject_GetVec4l,
	&iTestInteropObject_SetVec4f,
	&iTestInteropObject_GetVec4f,
	&iTestInteropObject_SetMatrixf,
	&iTestInteropObject_GetMatrixf,
	&iTestInteropObject_SetMatrixfValues,
	&iTestInteropObject_SetACharStrZ,
	&iTestInteropObject_GetACharStrZ,
	&iTestInteropObject_SetString,
	&iTestInteropObject_GetString,
	&iTestInteropObject_SetStringCRef,
	&iTestInteropObject_GetStringCRef,
	&iTestInteropObject_SetHString,
	&iTestInteropObject_GetHString,
	&iTestInteropObject_SetIndexedU32,
	&iTestInteropObject_GetIndexedU32,
	&iTestInteropObject_SetMappedU32,
	&iTestInteropObject_GetMappedU32,
	&iTestInteropObject_SetPtr,
	&iTestInteropObject_GetPtr,
	&iTestInteropObject_WriteRawBuffer,
	&iTestInteropObject_ReadRawBuffer,
	&iTestInteropObject_WriteRawBufferVoid,
	&iTestInteropObject_ReadRawBufferVoid,
	&iTestInteropObject_WriteRawBufferU32,
	&iTestInteropObject_ReadRawBufferU32,
	&iTestInteropObject_SetIndexedIUnknown,
	&iTestInteropObject_GetIndexedIUnknown,
	&iTestInteropObject_SetMappedIUnknown,
	&iTestInteropObject_GetMappedIUnknown,
	&iTestInteropObject_SetTestInteropObject,
	&iTestInteropObject_GetTestInteropObject,
	&iTestInteropObject_SetIndexedTestInteropObject,
	&iTestInteropObject_GetIndexedTestInteropObject,
	&iTestInteropObject_SetMappedTestInteropObject,
	&iTestInteropObject_GetMappedTestInteropObject,
	&iTestInteropObject_SetU32Vec,
	&iTestInteropObject_GetU32Vec,
	&iTestInteropObject_SetStringMap,
	&iTestInteropObject_GetStringMap,
	&iTestInteropObject_Func32,
	&iTestInteropObject_Func33,
	&iTestInteropObject_Func48,

};

//// Interface description //////////////////////////////////
static const ni::tUUID* Parents_iTestInteropObject[] = {
  &niGetInterfaceUUID(iUnknown),
};

static const ni::sInterfaceDef InterfaceDef_iTestInteropObject = {
  niGetInterfaceID(iTestInteropObject),
  &niGetInterfaceUUID(iTestInteropObject),
  1,
  Parents_iTestInteropObject,
  niCountOf(Methods_iTestInteropObject),Methods_iTestInteropObject,
  NULL
};

	return &InterfaceDef_iTestInteropObject;
}

// End of iTestInteropObject wrapper


//////////////////////////////////////////////////////////////////////////////////////////////
// iTestInteropSink wrapper
//////////////////////////////////////////////////////////////////////////////////////////////
niExportFunc(const ni::sInterfaceDef*) GetInterfaceDef_iTestInteropSink() {

// Method: OnTestInteropSink_Void
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Void = {
  "OnTestInteropSink_Void",
  0|ni::eType_Null, NULL, "void",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Void)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Void_I32
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Void_I32_Parameters[1] = { 
  { "v", ni::eType_I32, NULL, "ni::tI32" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Void_I32 = {
  "OnTestInteropSink_Void_I32",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Null, NULL, "void",
  1, iTestInteropSink_OnTestInteropSink_Void_I32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Void_I32)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Void_I64
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Void_I64_Parameters[1] = { 
  { "v", ni::eType_I64, NULL, "ni::tI64" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Void_I64 = {
  "OnTestInteropSink_Void_I64",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Null, NULL, "void",
  1, iTestInteropSink_OnTestInteropSink_Void_I64_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Void_I64)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Void_Ptr
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Void_Ptr_Parameters[1] = { 
  { "v", ni::eType_IntPtr, NULL, "ni::tIntPtr" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Void_Ptr = {
  "OnTestInteropSink_Void_Ptr",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Null, NULL, "void",
  1, iTestInteropSink_OnTestInteropSink_Void_Ptr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Void_Ptr)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Var_Var
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Var_Var_Parameters[1] = { 
  { "v", ni::eTypeFlags_Constant|ni::eType_Variant|ni::eTypeFlags_Pointer, NULL, "const ni::Var&" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Var_Var = {
  "OnTestInteropSink_Var_Var",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Variant, NULL, "ni::Var",
  1, iTestInteropSink_OnTestInteropSink_Var_Var_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Var_Var)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Vec3f_String
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Vec3f_String_Parameters[1] = { 
  { "aaszStr", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const ni::achar*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Vec3f_String = {
  "OnTestInteropSink_Vec3f_String",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Vec3f, NULL, "sVec3f",
  1, iTestInteropSink_OnTestInteropSink_Vec3f_String_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Vec3f_String)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Vec3f_CObject
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Vec3f_CObject_Parameters[1] = { 
  { "apObj", ni::eTypeFlags_Constant|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "const iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Vec3f_CObject = {
  "OnTestInteropSink_Vec3f_CObject",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Vec3f, NULL, "sVec3f",
  1, iTestInteropSink_OnTestInteropSink_Vec3f_CObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Vec3f_CObject)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Vec3f_Object
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Vec3f_Object_Parameters[1] = { 
  { "apObj", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Vec3f_Object = {
  "OnTestInteropSink_Vec3f_Object",
  ni::eTypeFlags_MethodOptional|0|ni::eType_Vec3f, NULL, "sVec3f",
  1, iTestInteropSink_OnTestInteropSink_Vec3f_Object_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Vec3f_Object)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Object_CObject
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Object_CObject_Parameters[1] = { 
  { "apObj", ni::eTypeFlags_Constant|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "const iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Object_CObject = {
  "OnTestInteropSink_Object_CObject",
  ni::eTypeFlags_MethodOptional|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropSink_OnTestInteropSink_Object_CObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Object_CObject)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Object_Object
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Object_Object_Parameters[1] = { 
  { "apObj", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Object_Object = {
  "OnTestInteropSink_Object_Object",
  ni::eTypeFlags_MethodOptional|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropSink_OnTestInteropSink_Object_Object_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Object_Object)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Object_Object2
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Object_Object2_Parameters[3] = { 
  { "a", ni::eType_U32, NULL, "ni::tU32" }, 
  { "b", ni::eType_F32, NULL, "ni::tF32" }, 
  { "apObj", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Object_Object2 = {
  "OnTestInteropSink_Object_Object2",
  ni::eTypeFlags_MethodOptional|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  3, iTestInteropSink_OnTestInteropSink_Object_Object2_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Object_Object2)
#else
  NULL
#endif
};

// Method: OnTestInteropSink_Object_ObjectVec3f
static const ni::sParameterDef iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f_Parameters[2] = { 
  { "apObj", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*" }, 
  { "c", ni::eTypeFlags_Constant|ni::eType_Vec3f|ni::eTypeFlags_Pointer, NULL, "const ni::sVec3f&" }
}; 
static const ni::sMethodDef iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f = {
  "OnTestInteropSink_Object_ObjectVec3f",
  ni::eTypeFlags_MethodOptional|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  2, iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f)
#else
  NULL
#endif
};

static const ni::sMethodDef* Methods_iTestInteropSink[] = {
	&iTestInteropSink_OnTestInteropSink_Void,
	&iTestInteropSink_OnTestInteropSink_Void_I32,
	&iTestInteropSink_OnTestInteropSink_Void_I64,
	&iTestInteropSink_OnTestInteropSink_Void_Ptr,
	&iTestInteropSink_OnTestInteropSink_Var_Var,
	&iTestInteropSink_OnTestInteropSink_Vec3f_String,
	&iTestInteropSink_OnTestInteropSink_Vec3f_CObject,
	&iTestInteropSink_OnTestInteropSink_Vec3f_Object,
	&iTestInteropSink_OnTestInteropSink_Object_CObject,
	&iTestInteropSink_OnTestInteropSink_Object_Object,
	&iTestInteropSink_OnTestInteropSink_Object_Object2,
	&iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f,

};

//// Interface dispatch wrapper /////////////////////////////
struct niHidden DispatchWrapper_iTestInteropSink : public ni::cIUnknownImpl<ni::iTestInteropSink,ni::eIUnknownImplFlags_Aggregatable|ni::eIUnknownImplFlags_NoRefCount>
{
	DispatchWrapper_iTestInteropSink(ni::iDispatch* apDispatch) {
    mprotected_pAggregateParent = apDispatch;
	}
	~DispatchWrapper_iTestInteropSink() {
    this->Invalidate();
  }

	ni::iUnknown* __stdcall QueryInterface(const ni::tUUID& aIID) niImpl {
    if (aIID == niGetInterfaceUUID(iTestInteropSink))
      return this;
		return mprotected_pAggregateParent->QueryInterface(aIID);
	}
	void __stdcall ListInterfaces(ni::iMutableCollection* apLst, ni::tU32 anFlags) const niImpl {
    apLst->Add(niGetInterfaceUUID(iTestInteropSink));
		mprotected_pAggregateParent->ListInterfaces(apLst,anFlags);
	}

  // Method (0): iTestInteropSink::OnTestInteropSink_Void
  void __stdcall OnTestInteropSink_Void() {
    ((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Void,0,NULL,0,NULL);
	}

  // Method (1): iTestInteropSink::OnTestInteropSink_Void_I32
  void __stdcall OnTestInteropSink_Void_I32(ni::tI32 v) {
    ni::Var _params_[1];
    _params_[0] = v;
    ((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Void_I32,1,_params_,1,NULL);
	}

  // Method (2): iTestInteropSink::OnTestInteropSink_Void_I64
  void __stdcall OnTestInteropSink_Void_I64(ni::tI64 v) {
    ni::Var _params_[1];
    _params_[0] = v;
    ((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Void_I64,2,_params_,1,NULL);
	}

  // Method (3): iTestInteropSink::OnTestInteropSink_Void_Ptr
  void __stdcall OnTestInteropSink_Void_Ptr(ni::tIntPtr v) {
    ni::Var _params_[1];
    _params_[0] = v;
    ((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Void_Ptr,3,_params_,1,NULL);
	}

  // Method (4): iTestInteropSink::OnTestInteropSink_Var_Var
  ni::Var __stdcall OnTestInteropSink_Var_Var(const ni::Var & v) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = v;
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Var_Var,4,_params_,1,&_var_)) {
  return _var_;
  }
    return niVarNull;
	}

  // Method (5): iTestInteropSink::OnTestInteropSink_Vec3f_String
  sVec3f __stdcall OnTestInteropSink_Vec3f_String(const ni::achar * aaszStr) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = aaszStr;
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Vec3f_String,5,_params_,1,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Vec3f_String.mReturnType,ni::eFalse)) {
        return _var_.GetVec3f();
      }
    }
    return ni::sVec3f::Zero();
	}

  // Method (6): iTestInteropSink::OnTestInteropSink_Vec3f_CObject
  sVec3f __stdcall OnTestInteropSink_Vec3f_CObject(const iTestInteropObject * apObj) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = niIUnknownCCast(apObj);
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Vec3f_CObject,6,_params_,1,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Vec3f_CObject.mReturnType,ni::eFalse)) {
        return _var_.GetVec3f();
      }
    }
    return ni::sVec3f::Zero();
	}

  // Method (7): iTestInteropSink::OnTestInteropSink_Vec3f_Object
  sVec3f __stdcall OnTestInteropSink_Vec3f_Object(iTestInteropObject * apObj) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = niIUnknownCast(apObj);
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Vec3f_Object,7,_params_,1,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Vec3f_Object.mReturnType,ni::eFalse)) {
        return _var_.GetVec3f();
      }
    }
    return ni::sVec3f::Zero();
	}

  // Method (8): iTestInteropSink::OnTestInteropSink_Object_CObject
  iTestInteropObject * __stdcall OnTestInteropSink_Object_CObject(const iTestInteropObject * apObj) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = niIUnknownCCast(apObj);
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Object_CObject,8,_params_,1,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Object_CObject.mReturnType,ni::eFalse)) {
        return (iTestInteropObject *)_var_.GetRawIUnknownPointerAndSetNull();
      }
    }
    return NULL;
	}

  // Method (9): iTestInteropSink::OnTestInteropSink_Object_Object
  iTestInteropObject * __stdcall OnTestInteropSink_Object_Object(iTestInteropObject * apObj) {
    ni::Var _var_;
    ni::Var _params_[1];
    _params_[0] = niIUnknownCast(apObj);
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Object_Object,9,_params_,1,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Object_Object.mReturnType,ni::eFalse)) {
        return (iTestInteropObject *)_var_.GetRawIUnknownPointerAndSetNull();
      }
    }
    return NULL;
	}

  // Method (10): iTestInteropSink::OnTestInteropSink_Object_Object2
  iTestInteropObject * __stdcall OnTestInteropSink_Object_Object2(ni::tU32 a, ni::tF32 b, iTestInteropObject * apObj) {
    ni::Var _var_;
    ni::Var _params_[3];
    _params_[0] = a;
    _params_[1] = b;
    _params_[2] = niIUnknownCast(apObj);
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Object_Object2,10,_params_,3,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Object_Object2.mReturnType,ni::eFalse)) {
        return (iTestInteropObject *)_var_.GetRawIUnknownPointerAndSetNull();
      }
    }
    return NULL;
	}

  // Method (11): iTestInteropSink::OnTestInteropSink_Object_ObjectVec3f
  iTestInteropObject * __stdcall OnTestInteropSink_Object_ObjectVec3f(iTestInteropObject * apObj, const ni::sVec3f & c) {
    ni::Var _var_;
    ni::Var _params_[2];
    _params_[0] = niIUnknownCast(apObj);
    _params_[1] = c;
    if (((ni::iDispatch*)(mprotected_pAggregateParent))->CallMethod(&iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f,11,_params_,2,&_var_)) {
      if (VarIsType(&_var_,iTestInteropSink_OnTestInteropSink_Object_ObjectVec3f.mReturnType,ni::eFalse)) {
        return (iTestInteropObject *)_var_.GetRawIUnknownPointerAndSetNull();
      }
    }
    return NULL;
	}

	static ni::iUnknown* Create(ni::iDispatch* apDispatch) {
		niAssert(niIsOK(apDispatch));
    if (!apDispatch->InitializeMethods(Methods_iTestInteropSink, niCountOf(Methods_iTestInteropSink))) {
      niError(niFmt("Can't initialize dispatch methods for %s.",  "iTestInteropSink"));
      return NULL;
    }
		return niNew DispatchWrapper_iTestInteropSink(apDispatch);
	}
};

//// Interface description //////////////////////////////////
static const ni::tUUID* Parents_iTestInteropSink[] = {
  &niGetInterfaceUUID(iUnknown),
};

static const ni::sInterfaceDef InterfaceDef_iTestInteropSink = {
  niGetInterfaceID(iTestInteropSink),
  &niGetInterfaceUUID(iTestInteropSink),
  1,
  Parents_iTestInteropSink,
  niCountOf(Methods_iTestInteropSink),Methods_iTestInteropSink,
  DispatchWrapper_iTestInteropSink::Create
};

	return &InterfaceDef_iTestInteropSink;
}

// End of iTestInteropSink wrapper


//////////////////////////////////////////////////////////////////////////////////////////////
// iTestInteropForEach wrapper
//////////////////////////////////////////////////////////////////////////////////////////////
niExportFunc(const ni::sInterfaceDef*) GetInterfaceDef_iTestInteropForEach() {

// Method: ForEachObject_OnTestInteropSink_Void
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Parameters[1] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void = {
  "ForEachObject_OnTestInteropSink_Void",
  0|ni::eType_Null, NULL, "void",
  1, iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Void)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Void_I32
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I32_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "v", ni::eType_I32, NULL, "ni::tI32" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I32 = {
  "ForEachObject_OnTestInteropSink_Void_I32",
  0|ni::eType_Null, NULL, "void",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I32_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I32)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Void_I64
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I64_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "v", ni::eType_I64, NULL, "ni::tI64" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I64 = {
  "ForEachObject_OnTestInteropSink_Void_I64",
  0|ni::eType_Null, NULL, "void",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I64_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I64)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Void_Ptr
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Ptr_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "v", ni::eType_Ptr, NULL, "ni::tPtr" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Ptr = {
  "ForEachObject_OnTestInteropSink_Void_Ptr",
  0|ni::eType_Null, NULL, "void",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Ptr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Ptr)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Var_Var
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Var_Var_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "v", ni::eType_Variant, NULL, "Var" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Var_Var = {
  "ForEachObject_OnTestInteropSink_Var_Var",
  0|ni::eType_Variant, NULL, "Var",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Var_Var_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Var_Var)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Vec3f_String
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_String_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "aaszStr", ni::eTypeFlags_Constant|ni::eType_AChar|ni::eTypeFlags_Pointer, NULL, "const ni::achar*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_String = {
  "ForEachObject_OnTestInteropSink_Vec3f_String",
  0|ni::eType_Vec3f, NULL, "sVec3f",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_String_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_String)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Vec3f_CObject
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_CObject_Parameters[1] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_CObject = {
  "ForEachObject_OnTestInteropSink_Vec3f_CObject",
  0|ni::eType_Vec3f, NULL, "sVec3f",
  1, iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_CObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_CObject)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Vec3f_Object
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_Object_Parameters[1] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_Object = {
  "ForEachObject_OnTestInteropSink_Vec3f_Object",
  0|ni::eType_Vec3f, NULL, "sVec3f",
  1, iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_Object_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_Object)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Object_CObject
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_CObject_Parameters[1] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_CObject = {
  "ForEachObject_OnTestInteropSink_Object_CObject",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_CObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_CObject)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Object_Object
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object_Parameters[1] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object = {
  "ForEachObject_OnTestInteropSink_Object_Object",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Object_Object2
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object2_Parameters[3] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "a", ni::eType_U32, NULL, "ni::tU32" }, 
  { "b", ni::eType_F32, NULL, "ni::tF32" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object2 = {
  "ForEachObject_OnTestInteropSink_Object_Object2",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  3, iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object2_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object2)
#else
  NULL
#endif
};

// Method: ForEachObject_OnTestInteropSink_Object_ObjectVec3f
static const ni::sParameterDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_ObjectVec3f_Parameters[2] = { 
  { "apSink", ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropSink), "iTestInteropSink*" }, 
  { "v", ni::eTypeFlags_Constant|ni::eType_Vec3f|ni::eTypeFlags_Pointer, NULL, "const ni::sVec3f&" }
}; 
static const ni::sMethodDef iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_ObjectVec3f = {
  "ForEachObject_OnTestInteropSink_Object_ObjectVec3f",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  2, iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_ObjectVec3f_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_ObjectVec3f)
#else
  NULL
#endif
};

static const ni::sMethodDef* Methods_iTestInteropForEach[] = {
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Void,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I32,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_I64,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Void_Ptr,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Var_Var,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_String,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_CObject,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Vec3f_Object,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_CObject,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_Object2,
	&iTestInteropForEach_ForEachObject_OnTestInteropSink_Object_ObjectVec3f,

};

//// Interface description //////////////////////////////////
static const ni::tUUID* Parents_iTestInteropForEach[] = {
  &niGetInterfaceUUID(iUnknown),
};

static const ni::sInterfaceDef InterfaceDef_iTestInteropForEach = {
  niGetInterfaceID(iTestInteropForEach),
  &niGetInterfaceUUID(iTestInteropForEach),
  1,
  Parents_iTestInteropForEach,
  niCountOf(Methods_iTestInteropForEach),Methods_iTestInteropForEach,
  NULL
};

	return &InterfaceDef_iTestInteropForEach;
}

// End of iTestInteropForEach wrapper


//////////////////////////////////////////////////////////////////////////////////////////////
// iTestInterop wrapper
//////////////////////////////////////////////////////////////////////////////////////////////
niExportFunc(const ni::sInterfaceDef*) GetInterfaceDef_iTestInterop() {

#if niMinFeatures(200)
// Method: FeatureSetNeverThere
static const ni::sMethodDef iTestInterop_FeatureSetNeverThere = {
  "FeatureSetNeverThere",
  0|ni::eType_Null, NULL, "void",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_FeatureSetNeverThere)
#else
  NULL
#endif
};
#endif // niMinFeatures(200)

#if niMinFeatures(30)
// Method: FeatureSetFull
static const ni::sMethodDef iTestInterop_FeatureSetFull = {
  "FeatureSetFull",
  0|ni::eType_Null, NULL, "void",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_FeatureSetFull)
#else
  NULL
#endif
};
#endif // niMinFeatures(30)

#if niMinFeatures(20)
// Method: FeatureSetEmbedded
static const ni::sMethodDef iTestInterop_FeatureSetEmbedded = {
  "FeatureSetEmbedded",
  0|ni::eType_Null, NULL, "void",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_FeatureSetEmbedded)
#else
  NULL
#endif
};
#endif // niMinFeatures(20)

// Method: FeatureSetLight
static const ni::sMethodDef iTestInterop_FeatureSetLight = {
  "FeatureSetLight",
  0|ni::eType_Null, NULL, "void",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_FeatureSetLight)
#else
  NULL
#endif
};

// Method: GenerateCrash
static const ni::sParameterDef iTestInterop_GenerateCrash_Parameters[1] = { 
  { "anExceptionType", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInterop_GenerateCrash = {
  "GenerateCrash",
  0|ni::eType_Int, NULL, "tInt",
  1, iTestInterop_GenerateCrash_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_GenerateCrash)
#else
  NULL
#endif
};

// Method: GetNumTestInteropObjects
static const ni::sMethodDef iTestInterop_GetNumTestInteropObjects = {
  "GetNumTestInteropObjects",
  ni::eTypeFlags_MethodGetter|0|ni::eType_Size, NULL, "tSize",
  0, NULL,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_GetNumTestInteropObjects)
#else
  NULL
#endif
};

// Method: GetTestInteropObject
static const ni::sParameterDef iTestInterop_GetTestInteropObject_Parameters[1] = { 
  { "anIndex", ni::eType_Size, NULL, "ni::tSize" }
}; 
static const ni::sMethodDef iTestInterop_GetTestInteropObject = {
  "GetTestInteropObject",
  ni::eTypeFlags_MethodGetter|0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInterop_GetTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_GetTestInteropObject)
#else
  NULL
#endif
};

// Method: CreateTestInteropObject
static const ni::sParameterDef iTestInterop_CreateTestInteropObject_Parameters[1] = { 
  { "anNumItems", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInterop_CreateTestInteropObject = {
  "CreateTestInteropObject",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "iTestInteropObject*",
  1, iTestInterop_CreateTestInteropObject_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_CreateTestInteropObject)
#else
  NULL
#endif
};

// Method: CreateTestInteropObjectPtr
static const ni::sParameterDef iTestInterop_CreateTestInteropObjectPtr_Parameters[1] = { 
  { "anNumItems", ni::eType_U32, NULL, "ni::tU32" }
}; 
static const ni::sMethodDef iTestInterop_CreateTestInteropObjectPtr = {
  "CreateTestInteropObjectPtr",
  0|ni::eType_IUnknown|ni::eTypeFlags_Pointer, &niGetInterfaceUUID(iTestInteropObject), "Ptr<iTestInteropObject>",
  1, iTestInterop_CreateTestInteropObjectPtr_Parameters,
#ifndef niConfig_NoXCALL
  XCALL_CIMPL(iTestInterop_CreateTestInteropObjectPtr)
#else
  NULL
#endif
};

static const ni::sMethodDef* Methods_iTestInterop[] = {
#if niMinFeatures(200)
	&iTestInterop_FeatureSetNeverThere,
#endif // niMinFeatures(200)
#if niMinFeatures(30)
	&iTestInterop_FeatureSetFull,
#endif // niMinFeatures(30)
#if niMinFeatures(20)
	&iTestInterop_FeatureSetEmbedded,
#endif // niMinFeatures(20)
	&iTestInterop_FeatureSetLight,
	&iTestInterop_GenerateCrash,
	&iTestInterop_GetNumTestInteropObjects,
	&iTestInterop_GetTestInteropObject,
	&iTestInterop_CreateTestInteropObject,
	&iTestInterop_CreateTestInteropObjectPtr,

};

//// Interface description //////////////////////////////////
static const ni::tUUID* Parents_iTestInterop[] = {
  &niGetInterfaceUUID(iTestInteropForEach),
};

static const ni::sInterfaceDef InterfaceDef_iTestInterop = {
  niGetInterfaceID(iTestInterop),
  &niGetInterfaceUUID(iTestInterop),
  1,
  Parents_iTestInterop,
  niCountOf(Methods_iTestInterop),Methods_iTestInterop,
  NULL
};

	return &InterfaceDef_iTestInterop;
}

// End of iTestInterop wrapper

#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef


//////////////////////////////////////////////////////////////////////////////////////////////
// Enumerations definition
//////////////////////////////////////////////////////////////////////////////////////////////
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoEnumDef

// --- eTestInterop ---
#if niMinFeatures(1)
niExportFunc(const ni::sEnumDef*) GetEnumDef_eTestInterop() {

static const ni::sEnumValueDef Enum_eTestInterop_Values[] = {
#if niMinFeatures(1)
	{ "A", ni::eTestInterop_A },
#endif // niMinFeatures(1)
#if niMinFeatures(1)
	{ "B", ni::eTestInterop_B },
#endif // niMinFeatures(1)
#if niMinFeatures(30)
	{ "C", ni::eTestInterop_C },
#endif // niMinFeatures(30)
#if niMinFeatures(200)
	{ "NeverThere", ni::eTestInterop_NeverThere },
#endif // niMinFeatures(200)
};
static const ni::sEnumDef Enum_eTestInterop = {
	"eTestInterop",
  niCountOf(Enum_eTestInterop_Values), Enum_eTestInterop_Values
};

	return &Enum_eTestInterop;
}
#endif // niMinFeatures(1)

// --- eTestInteropFlags ---
niExportFunc(const ni::sEnumDef*) GetEnumDef_eTestInteropFlags() {

static const ni::sEnumValueDef Enum_eTestInteropFlags_Values[] = {
	{ "A", ni::eTestInteropFlags_A },
	{ "B", ni::eTestInteropFlags_B },
	{ "C", ni::eTestInteropFlags_C },
	{ "All", ni::eTestInteropFlags_All },
};
static const ni::sEnumDef Enum_eTestInteropFlags = {
	"eTestInteropFlags",
  niCountOf(Enum_eTestInteropFlags_Values), Enum_eTestInteropFlags_Values
};

	return &Enum_eTestInteropFlags;
}
#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoEnumDef


//////////////////////////////////////////////////////////////////////////////////////////////
// Constants definition
//////////////////////////////////////////////////////////////////////////////////////////////
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoConstDef

#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoConstDef

//////////////////////////////////////////////////////////////////////////////////////////////
// GetModuleDef
//////////////////////////////////////////////////////////////////////////////////////////////
niExportFunc(const ni::iModuleDef*) GetModuleDef_niTestInterop()
{
  static bool _initialized = false;
  if (!_initialized) {
    _initialized = true;
    niModuleDefImpl_GetModule_Register();
  }

//////////////////////////////////////////////////////////////////////////////////////////////
// Object types definition
//////////////////////////////////////////////////////////////////////////////////////////////
static const ni::sObjectTypeDef ObjectType__TestInterop("niTestInterop.TestInterop",New_niTestInterop_TestInterop);


//////////////////////////////////////////////////////////////////////////////////////////////
// Module definition
//////////////////////////////////////////////////////////////////////////////////////////////
static const ni::achar* Dependencies[] = {
  "niLang",
};
static const ni::sObjectTypeDef* ObjectTypes[] = {
  &ObjectType__TestInterop,
};

#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef
static const ni::sInterfaceDef* Interfaces[] = {
  GetInterfaceDef_iTestInteropObject(),
  GetInterfaceDef_iTestInteropSink(),
  GetInterfaceDef_iTestInteropForEach(),
  GetInterfaceDef_iTestInterop(),
};

#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef

#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoEnumDef
static const ni::sEnumDef* Enumerations[] = {
#if niMinFeatures(1)
  GetEnumDef_eTestInterop(),
#endif // niMinFeatures(1)
  GetEnumDef_eTestInteropFlags(),
};

#endif // #if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoEnumDef

static const ni::sModuleDef ModuleDef(
  "niTestInterop",
  "1,0,0",
  "TestInterop module (Build Date: " __DATE__ ")",
  "niLang Authors",
  "(c) 2022 The niLang Authors",
  1, Dependencies,
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoInterfaceDef
  niCountOf(Interfaces), Interfaces,
#else
	0, NULL,
#endif
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoEnumDef
  niCountOf(Enumerations), Enumerations,
#else
	0, NULL,
#endif
#if !defined niConfig_OnlyObjectTypesIDL && !defined niConfig_NoConstDef
  0, NULL,
#else
	0, NULL,
#endif
  niCountOf(ObjectTypes), ObjectTypes
);

  return &ModuleDef;
}	// End of GetModuleDef_niTestInterop
} // end of namespace ni

/// EOF //////////////////////////////////////////////////////////////////////////////////////
#include <niLang/Utils/ModuleDefImpl_End.h>
