// clang-format off
#ifndef __MODULEDEF_niScriptCpp_H__
#define __MODULEDEF_niScriptCpp_H__
/*
 * Autogenerated module definition for ni::niScriptCpp.
 */

#include <niLang/ObjModel.h>

namespace ni {
/** \addtogroup niLang
 * @{
 */

static const char *const kVersion_niScriptCpp = "1,0,0";
niExportFunc(const ni::iModuleDef*) GetModuleDef_niScriptCpp();
niExportFunc(ni::iUnknown*) New_niScriptCpp_ScriptingHost(const ni::Var&, const ni::Var&);



/**@}*/
} // end of namespace ni

/// EOF //////////////////////////////////////////////////////////////////////////////////////
#endif /// __MODULEDEF_niScriptCpp_H__
