// clang-format off
//
// Autogenerated IDL definition for 'API/niUI/IRay.h'.
//
#include "../API/niUI/IRay.h"

#ifndef IDLC_BEGIN_NAMESPACE
#error "IDLC_BEGIN_NAMESPACE not defined !"
#endif
#ifndef IDLC_END_NAMESPACE
#error "IDLC_END_NAMESPACE not defined !"
#endif

IDLC_BEGIN_NAMESPACE()

/** NAMESPACE : ni **/
/** interface : iRayPrimitivesDesc **/
IDLC_BEGIN_INTF(ni,iRayPrimitivesDesc)
/** ni -> iRayPrimitivesDesc::GetNumPrimitives/0 **/
IDLC_METH_BEGIN(ni,iRayPrimitivesDesc,GetNumPrimitives,0)
	IDLC_DECL_RETVAR(tU32,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPrimitivesDesc,GetNumPrimitives,0,())
	IDLC_RET_FROM_BASE(ni::eType_U32,_Ret)
IDLC_METH_END(ni,iRayPrimitivesDesc,GetNumPrimitives,0)

/** ni -> iRayPrimitivesDesc::AddTriangles/7 **/
IDLC_METH_BEGIN(ni,iRayPrimitivesDesc,AddTriangles,7)
	IDLC_DECL_VAR(iGpuBuffer*,apVertices)
	IDLC_BUF_TO_INTF(iGpuBuffer,apVertices)
	IDLC_DECL_VAR(tU32,anVertexOffset)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexOffset)
	IDLC_DECL_VAR(tU32,anVertexStride)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexStride)
	IDLC_DECL_VAR(tU32,anVertexCount)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexCount)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_VAR(tRayPrimitiveFlags,aFlags)
	IDLC_BUF_TO_ENUM(tRayPrimitiveFlags,aFlags)
	IDLC_DECL_VAR(tU32,anHitGroup)
	IDLC_BUF_TO_BASE(ni::eType_U32,anHitGroup)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPrimitivesDesc,AddTriangles,7,(apVertices,anVertexOffset,anVertexStride,anVertexCount,aTransform,aFlags,anHitGroup))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayPrimitivesDesc,AddTriangles,7)

/** ni -> iRayPrimitivesDesc::AddTrianglesIndexed/11 **/
IDLC_METH_BEGIN(ni,iRayPrimitivesDesc,AddTrianglesIndexed,11)
	IDLC_DECL_VAR(iGpuBuffer*,apVertices)
	IDLC_BUF_TO_INTF(iGpuBuffer,apVertices)
	IDLC_DECL_VAR(tU32,anVertexOffset)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexOffset)
	IDLC_DECL_VAR(tU32,anVertexStride)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexStride)
	IDLC_DECL_VAR(tU32,anVertexCount)
	IDLC_BUF_TO_BASE(ni::eType_U32,anVertexCount)
	IDLC_DECL_VAR(iGpuBuffer*,apIndices)
	IDLC_BUF_TO_INTF(iGpuBuffer,apIndices)
	IDLC_DECL_VAR(tU32,anIndexOffset)
	IDLC_BUF_TO_BASE(ni::eType_U32,anIndexOffset)
	IDLC_DECL_VAR(eGpuIndexType,anIndexType)
	IDLC_BUF_TO_ENUM(eGpuIndexType,anIndexType)
	IDLC_DECL_VAR(tU32,anIndexCount)
	IDLC_BUF_TO_BASE(ni::eType_U32,anIndexCount)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_VAR(tRayPrimitiveFlags,aFlags)
	IDLC_BUF_TO_ENUM(tRayPrimitiveFlags,aFlags)
	IDLC_DECL_VAR(tU32,anHitGroup)
	IDLC_BUF_TO_BASE(ni::eType_U32,anHitGroup)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPrimitivesDesc,AddTrianglesIndexed,11,(apVertices,anVertexOffset,anVertexStride,anVertexCount,apIndices,anIndexOffset,anIndexType,anIndexCount,aTransform,aFlags,anHitGroup))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayPrimitivesDesc,AddTrianglesIndexed,11)

/** ni -> iRayPrimitivesDesc::AddProceduralAABBs/7 **/
IDLC_METH_BEGIN(ni,iRayPrimitivesDesc,AddProceduralAABBs,7)
	IDLC_DECL_VAR(iGpuBuffer*,apAABBs)
	IDLC_BUF_TO_INTF(iGpuBuffer,apAABBs)
	IDLC_DECL_VAR(tU32,anAABBOffset)
	IDLC_BUF_TO_BASE(ni::eType_U32,anAABBOffset)
	IDLC_DECL_VAR(tU32,anAABBStride)
	IDLC_BUF_TO_BASE(ni::eType_U32,anAABBStride)
	IDLC_DECL_VAR(tU32,anAABBCount)
	IDLC_BUF_TO_BASE(ni::eType_U32,anAABBCount)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_VAR(tRayPrimitiveFlags,aFlags)
	IDLC_BUF_TO_ENUM(tRayPrimitiveFlags,aFlags)
	IDLC_DECL_VAR(tU32,anHitGroup)
	IDLC_BUF_TO_BASE(ni::eType_U32,anHitGroup)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPrimitivesDesc,AddProceduralAABBs,7,(apAABBs,anAABBOffset,anAABBStride,anAABBCount,aTransform,aFlags,anHitGroup))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayPrimitivesDesc,AddProceduralAABBs,7)

IDLC_END_INTF(ni,iRayPrimitivesDesc)

/** interface : iRayPrimitives **/
IDLC_BEGIN_INTF(ni,iRayPrimitives)
IDLC_END_INTF(ni,iRayPrimitives)

/** interface : iRayInstancesDesc **/
IDLC_BEGIN_INTF(ni,iRayInstancesDesc)
/** ni -> iRayInstancesDesc::GetNumInstances/0 **/
IDLC_METH_BEGIN(ni,iRayInstancesDesc,GetNumInstances,0)
	IDLC_DECL_RETVAR(tU32,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayInstancesDesc,GetNumInstances,0,())
	IDLC_RET_FROM_BASE(ni::eType_U32,_Ret)
IDLC_METH_END(ni,iRayInstancesDesc,GetNumInstances,0)

/** ni -> iRayInstancesDesc::AddInstance/6 **/
IDLC_METH_BEGIN(ni,iRayInstancesDesc,AddInstance,6)
	IDLC_DECL_VAR(iRayPrimitives*,apAS)
	IDLC_BUF_TO_INTF(iRayPrimitives,apAS)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_VAR(tU32,anCustomInstanceId)
	IDLC_BUF_TO_BASE(ni::eType_U32,anCustomInstanceId)
	IDLC_DECL_VAR(tU8,anMask)
	IDLC_BUF_TO_BASE(ni::eType_U8,anMask)
	IDLC_DECL_VAR(tU32,anHitGroup)
	IDLC_BUF_TO_BASE(ni::eType_U32,anHitGroup)
	IDLC_DECL_VAR(tRayInstanceFlags,aFlags)
	IDLC_BUF_TO_ENUM(tRayInstanceFlags,aFlags)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayInstancesDesc,AddInstance,6,(apAS,aTransform,anCustomInstanceId,anMask,anHitGroup,aFlags))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayInstancesDesc,AddInstance,6)

/** ni -> iRayInstancesDesc::UpdateInstance/6 **/
IDLC_METH_BEGIN(ni,iRayInstancesDesc,UpdateInstance,6)
	IDLC_DECL_VAR(tU32,anInstanceIndex)
	IDLC_BUF_TO_BASE(ni::eType_U32,anInstanceIndex)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_VAR(tU32,anCustomInstanceId)
	IDLC_BUF_TO_BASE(ni::eType_U32,anCustomInstanceId)
	IDLC_DECL_VAR(tU8,anMask)
	IDLC_BUF_TO_BASE(ni::eType_U8,anMask)
	IDLC_DECL_VAR(tU32,anHitGroup)
	IDLC_BUF_TO_BASE(ni::eType_U32,anHitGroup)
	IDLC_DECL_VAR(tRayInstanceFlags,aFlags)
	IDLC_BUF_TO_ENUM(tRayInstanceFlags,aFlags)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayInstancesDesc,UpdateInstance,6,(anInstanceIndex,aTransform,anCustomInstanceId,anMask,anHitGroup,aFlags))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayInstancesDesc,UpdateInstance,6)

/** ni -> iRayInstancesDesc::UpdateInstanceTransform/2 **/
IDLC_METH_BEGIN(ni,iRayInstancesDesc,UpdateInstanceTransform,2)
	IDLC_DECL_VAR(tU32,anInstanceIndex)
	IDLC_BUF_TO_BASE(ni::eType_U32,anInstanceIndex)
	IDLC_DECL_VAR(sMatrixf,aTransform)
	IDLC_BUF_TO_BASE(ni::eTypeFlags_Constant|ni::eType_Matrixf|ni::eTypeFlags_Pointer,aTransform)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayInstancesDesc,UpdateInstanceTransform,2,(anInstanceIndex,aTransform))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayInstancesDesc,UpdateInstanceTransform,2)

IDLC_END_INTF(ni,iRayInstancesDesc)

/** interface : iRayInstances **/
IDLC_BEGIN_INTF(ni,iRayInstances)
IDLC_END_INTF(ni,iRayInstances)

/** interface : iRayFunctionTable **/
IDLC_BEGIN_INTF(ni,iRayFunctionTable)
/** ni -> iRayFunctionTable::SetRayGenFunction/1 **/
IDLC_METH_BEGIN(ni,iRayFunctionTable,SetRayGenFunction,1)
	IDLC_DECL_VAR(iGpuFunction*,apFunction)
	IDLC_BUF_TO_INTF(iGpuFunction,apFunction)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayFunctionTable,SetRayGenFunction,1,(apFunction))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayFunctionTable,SetRayGenFunction,1)

/** ni -> iRayFunctionTable::SetMissFunction/1 **/
IDLC_METH_BEGIN(ni,iRayFunctionTable,SetMissFunction,1)
	IDLC_DECL_VAR(iGpuFunction*,apFunction)
	IDLC_BUF_TO_INTF(iGpuFunction,apFunction)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayFunctionTable,SetMissFunction,1,(apFunction))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayFunctionTable,SetMissFunction,1)

/** ni -> iRayFunctionTable::AddHitGroup/5 **/
IDLC_METH_BEGIN(ni,iRayFunctionTable,AddHitGroup,5)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_VAR(eRayFunctionGroupType,aType)
	IDLC_BUF_TO_ENUM(eRayFunctionGroupType,aType)
	IDLC_DECL_VAR(iGpuFunction*,apClosestHit)
	IDLC_BUF_TO_INTF(iGpuFunction,apClosestHit)
	IDLC_DECL_VAR(iGpuFunction*,apAnyHit)
	IDLC_BUF_TO_INTF(iGpuFunction,apAnyHit)
	IDLC_DECL_VAR(iGpuFunction*,apIntersection)
	IDLC_BUF_TO_INTF(iGpuFunction,apIntersection)
	IDLC_DECL_RETVAR(tU32,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayFunctionTable,AddHitGroup,5,(ahspName,aType,apClosestHit,apAnyHit,apIntersection))
	IDLC_RET_FROM_BASE(ni::eType_U32,_Ret)
IDLC_METH_END(ni,iRayFunctionTable,AddHitGroup,5)

IDLC_END_INTF(ni,iRayFunctionTable)

/** interface : iRayPipeline **/
IDLC_BEGIN_INTF(ni,iRayPipeline)
/** ni -> iRayPipeline::GetRayGenFunction/0 **/
IDLC_METH_BEGIN(ni,iRayPipeline,GetRayGenFunction,0)
	IDLC_DECL_RETVAR(iGpuFunction*,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPipeline,GetRayGenFunction,0,())
	IDLC_RET_FROM_INTF(iGpuFunction,_Ret)
IDLC_METH_END(ni,iRayPipeline,GetRayGenFunction,0)

/** ni -> iRayPipeline::GetMissFunction/0 **/
IDLC_METH_BEGIN(ni,iRayPipeline,GetMissFunction,0)
	IDLC_DECL_RETVAR(iGpuFunction*,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPipeline,GetMissFunction,0,())
	IDLC_RET_FROM_INTF(iGpuFunction,_Ret)
IDLC_METH_END(ni,iRayPipeline,GetMissFunction,0)

/** ni -> iRayPipeline::GetFunctionTable/0 **/
IDLC_METH_BEGIN(ni,iRayPipeline,GetFunctionTable,0)
	IDLC_DECL_RETVAR(iRayFunctionTable*,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayPipeline,GetFunctionTable,0,())
	IDLC_RET_FROM_INTF(iRayFunctionTable,_Ret)
IDLC_METH_END(ni,iRayPipeline,GetFunctionTable,0)

IDLC_END_INTF(ni,iRayPipeline)

/** interface : iRayBuildEncoder **/
IDLC_BEGIN_INTF(ni,iRayBuildEncoder)
/** ni -> iRayBuildEncoder::BuildRayPrimitives/2 **/
IDLC_METH_BEGIN(ni,iRayBuildEncoder,BuildRayPrimitives,2)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_VAR(iRayPrimitivesDesc*,apPrimitivesDesc)
	IDLC_BUF_TO_INTF(iRayPrimitivesDesc,apPrimitivesDesc)
	IDLC_DECL_RETVAR(Ptr<iRayPrimitives>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayBuildEncoder,BuildRayPrimitives,2,(ahspName,apPrimitivesDesc))
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iRayBuildEncoder,BuildRayPrimitives,2)

/** ni -> iRayBuildEncoder::BuildRayInstances/2 **/
IDLC_METH_BEGIN(ni,iRayBuildEncoder,BuildRayInstances,2)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_VAR(iRayInstancesDesc*,apInstancesDesc)
	IDLC_BUF_TO_INTF(iRayInstancesDesc,apInstancesDesc)
	IDLC_DECL_RETVAR(Ptr<iRayInstances>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayBuildEncoder,BuildRayInstances,2,(ahspName,apInstancesDesc))
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iRayBuildEncoder,BuildRayInstances,2)

IDLC_END_INTF(ni,iRayBuildEncoder)

/** interface : iRayCommandEncoder **/
IDLC_BEGIN_INTF(ni,iRayCommandEncoder)
/** ni -> iRayCommandEncoder::SetRayInstances/1 **/
IDLC_METH_BEGIN(ni,iRayCommandEncoder,SetRayInstances,1)
	IDLC_DECL_VAR(iRayInstances*,apAS)
	IDLC_BUF_TO_INTF(iRayInstances,apAS)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayCommandEncoder,SetRayInstances,1,(apAS))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayCommandEncoder,SetRayInstances,1)

/** ni -> iRayCommandEncoder::SetRayPipeline/1 **/
IDLC_METH_BEGIN(ni,iRayCommandEncoder,SetRayPipeline,1)
	IDLC_DECL_VAR(iRayPipeline*,apAS)
	IDLC_BUF_TO_INTF(iRayPipeline,apAS)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayCommandEncoder,SetRayPipeline,1,(apAS))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayCommandEncoder,SetRayPipeline,1)

/** ni -> iRayCommandEncoder::SetRayOutputImage/1 **/
IDLC_METH_BEGIN(ni,iRayCommandEncoder,SetRayOutputImage,1)
	IDLC_DECL_VAR(iTexture*,apOutputImage)
	IDLC_BUF_TO_INTF(iTexture,apOutputImage)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayCommandEncoder,SetRayOutputImage,1,(apOutputImage))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayCommandEncoder,SetRayOutputImage,1)

/** ni -> iRayCommandEncoder::DispatchRays/3 **/
IDLC_METH_BEGIN(ni,iRayCommandEncoder,DispatchRays,3)
	IDLC_DECL_VAR(tU32,anW)
	IDLC_BUF_TO_BASE(ni::eType_U32,anW)
	IDLC_DECL_VAR(tU32,anH)
	IDLC_BUF_TO_BASE(ni::eType_U32,anH)
	IDLC_DECL_VAR(tU32,anD)
	IDLC_BUF_TO_BASE(ni::eType_U32,anD)
	IDLC_DECL_RETVAR(tBool,_Ret)
	IDLC_METH_CALL(_Ret,ni,iRayCommandEncoder,DispatchRays,3,(anW,anH,anD))
	IDLC_RET_FROM_BASE(ni::eType_I8,_Ret)
IDLC_METH_END(ni,iRayCommandEncoder,DispatchRays,3)

IDLC_END_INTF(ni,iRayCommandEncoder)

/** interface : iGraphicsDriverRay **/
IDLC_BEGIN_INTF(ni,iGraphicsDriverRay)
/** ni -> iGraphicsDriverRay::CreateRayPipeline/2 **/
IDLC_METH_BEGIN(ni,iGraphicsDriverRay,CreateRayPipeline,2)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_VAR(iRayFunctionTable*,apFunctionTable)
	IDLC_BUF_TO_INTF(iRayFunctionTable,apFunctionTable)
	IDLC_DECL_RETVAR(Ptr<iRayPipeline>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iGraphicsDriverRay,CreateRayPipeline,2,(ahspName,apFunctionTable))
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iGraphicsDriverRay,CreateRayPipeline,2)

/** ni -> iGraphicsDriverRay::CreateRayFunctionTable/0 **/
IDLC_METH_BEGIN(ni,iGraphicsDriverRay,CreateRayFunctionTable,0)
	IDLC_DECL_RETVAR(Ptr<iRayFunctionTable>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iGraphicsDriverRay,CreateRayFunctionTable,0,())
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iGraphicsDriverRay,CreateRayFunctionTable,0)

/** ni -> iGraphicsDriverRay::CreateRayPrimitivesDesc/1 **/
IDLC_METH_BEGIN(ni,iGraphicsDriverRay,CreateRayPrimitivesDesc,1)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_RETVAR(Ptr<iRayPrimitivesDesc>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iGraphicsDriverRay,CreateRayPrimitivesDesc,1,(ahspName))
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iGraphicsDriverRay,CreateRayPrimitivesDesc,1)

/** ni -> iGraphicsDriverRay::CreateRayInstancesDesc/1 **/
IDLC_METH_BEGIN(ni,iGraphicsDriverRay,CreateRayInstancesDesc,1)
	IDLC_DECL_VAR(iHString*,ahspName)
	IDLC_BUF_TO_INTF(iHString,ahspName)
	IDLC_DECL_RETVAR(Ptr<iRayInstancesDesc>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iGraphicsDriverRay,CreateRayInstancesDesc,1,(ahspName))
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iGraphicsDriverRay,CreateRayInstancesDesc,1)

/** ni -> iGraphicsDriverRay::CreateRayBuildEncoder/0 **/
IDLC_METH_BEGIN(ni,iGraphicsDriverRay,CreateRayBuildEncoder,0)
	IDLC_DECL_RETVAR(Ptr<iRayBuildEncoder>,_Ret)
	IDLC_METH_CALL(_Ret,ni,iGraphicsDriverRay,CreateRayBuildEncoder,0,())
	IDLC_RET_FROM_INTF(,_Ret)
IDLC_METH_END(ni,iGraphicsDriverRay,CreateRayBuildEncoder,0)

IDLC_END_INTF(ni,iGraphicsDriverRay)

IDLC_END_NAMESPACE()
// EOF //
