name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu22:
    runs-on: ubuntu-22.04

    steps:
      - name: Check-out ham
        uses: actions/checkout@v4
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      - uses: actions/checkout@v4
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          ./ham/bin/ham -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/ham -X niLang -E BUILD=ra _run_ci.sh

  build_ubuntu24:
    runs-on: ubuntu-24.04

    steps:
      - name: Check-out ham
        uses: actions/checkout@v4
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      - uses: actions/checkout@v4
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          ./ham/bin/ham -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/ham -X niLang -E BUILD=ra _run_ci.sh

  build_macos15:
    runs-on: macos-15
    continue-on-error: true

    steps:
      - name: Check-out ham
        uses: actions/checkout@v4
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      - uses: actions/checkout@v4
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          ./ham/bin/ham -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/ham -X niLang -E BUILD=ra _run_ci.sh

  build_ios_on_macos15:
    runs-on: macos-15
    continue-on-error: true

    steps:
      - name: Check-out ham
        uses: actions/checkout@v4
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      - uses: actions/checkout@v4
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        run: |
          ./ham/bin/hamx :niLang BUILD_TARGET=ios-arm64 BUILD=da pass1 all

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/hamx :niLang BUILD_TARGET=ios-arm64 BUILD=ra pass1 all

  build_windows2019:
    runs-on: windows-2019

    steps:
      - name: Turn off git eol insanity on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check-out ham
        uses: actions/checkout@v4
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: ham-install-for-windows
        run: |
          .\ham\bin\ham-install-for-windows.cmd

      - name: ham-toolset repos cppm
        run: |
          .\ham\bin\ham-toolset.cmd repos cppm

      - uses: actions/checkout@v4
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          .\ham\bin\ham.cmd -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          .\ham\bin\ham.cmd -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          .\ham\bin\ham.cmd -X niLang -E BUILD=ra _run_ci.sh
