name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_ubuntu:
    runs-on: ubuntu-22.04

    steps:
      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          ./ham/bin/ham -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/ham -X niLang -E BUILD=ra _run_ci.sh

  build_macos:
    # Fix the macOS version to avoid surprise updates in macos-latest
    runs-on: macos-12

    steps:
      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install OS packages
        run: |
          ./ham/bin/ham-install-os-packages

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          ./ham/bin/ham -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          ./ham/bin/ham -X niLang -E BUILD=ra _run_ci.sh

  build_windows:
    # Fix the Windows version to avoid surprise updates in windows-latest
    runs-on: windows-2019

    steps:
      - name: Turn off git eol insanity on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: ham-install-for-windows
        run: |
          .\ham\bin\ham-install-for-windows.cmd

      - name: ham-toolset repos cppm
        run: |
          .\ham\bin\ham-toolset.cmd repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          .\ham\bin\ham.cmd -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          .\ham\bin\ham.cmd -X niLang -E BUILD=da _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          .\ham\bin\ham.cmd -X niLang -E BUILD=ra _run_ci.sh
