name: run_ci

concurrency:
  group: main-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Run on all push in main
  push:
    branches: [ main, master ]
  # Run on all pull requests
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_ubuntu20:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: Install Ubuntu packages
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt install -y clang curl ffmpeg freeglut3-dev g++ gcc git libcurl4-openssl-dev lftp libsdl2-dev libssl-dev libudev-dev mesa-common-dev mesa-utils ntpdate p7zip-full pkg-config python3 python3-pip subversion wget xsltproc libdw-dev libunwind-dev

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          ref: main
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          export BUILD=da
          ./ham/bin/ham -X niLang ./_run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          export BUILD=ra
          ./ham/bin/ham -X niLang ./_run_ci.sh

  build_macos_latest:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: ham-toolset repos cppm
        run: |
          ./ham/bin/ham-toolset repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          ref: main
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          ./ham/bin/ham -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          export BUILD=da
          ./ham/bin/ham -X niLang ./_run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          export BUILD=ra
          ./ham/bin/ham -X niLang ./_run_ci.sh

  build_windows_latest:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Turn off git eol insanity on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Check-out and init ham
      - name: Check-out ham
        uses: actions/checkout@v3
        with:
          repository: prenaux/ham
          ref: master
          path: ham

      - name: ham-install-for-windows
        run: |
          .\ham\bin\ham-install-for-windows.cmd

      - name: ham-toolset repos cppm
        run: |
          .\ham\bin\ham-toolset.cmd repos cppm

      # Check-out our repo
      - uses: actions/checkout@v3
        with:
          ref: main
          path: niLang

      - name: niLang _build_bootstrap.sh
        run: |
          .\ham\bin\ham.cmd -X niLang _build_bootstrap.sh

      - name: niLang _run_ci.sh BUILD=da
        continue-on-error: true
        run: |
          set BUILD=da
          .\ham\bin\ham.cmd -X niLang _run_ci.sh

      - name: niLang _run_ci.sh BUILD=ra
        run: |
          set BUILD=ra
          .\ham\bin\ham.cmd -X niLang _run_ci.sh
